### ISSUE TITLE
[Suggestion] use the rpi-vk-driver for the rpi<4

### ISSUE THREAD

**Issue by k0st1x** [LibreELEC/LibreELEC.tv#4443]
for the further purposes to use the vulkan soft, plz include the rpi-vk-driver into the installation
https://github.com/Yours3lf/rpi-vk-driver/releases/tag/v1.0
(rpi2,rpi3)
can you provide a build with such driver? or some description how to get and install it into the libreelec on rpi?

**Comment by DaVukovic** [comment]
Thanks for you report. 

Unfortunately I have to say that this is an "issue"-tracker. Your report sounds more like a feature request to me.Feature requests have to be submitted at forums at the specific sub-section: https://forum.libreelec.tv/board/18-feature-requests/

Thanks for understanding
