### ISSUE TITLE
[BUG] need to re-select HDMI input, or got black screen after LibreELEC splash logo

### ISSUE THREAD

**Issue by efa** [LibreELEC/LibreELEC.tv#4526]
### Describe the bug

Need to re-select the TV HDMI input to see the Kodi menu,
because at boot after the LibreELEC splash logo, I always got a permanent black screen,
when selected 1680x1050p@60.00Hz for Kodi, that is the TV native resolution.

### To Reproduce
1. Boot the Raspberry Pi to LibreELEC
2. wait LibreElec splash logo
3. after 40 s, the TV always become black, and start a static noise
4. I can't see the Kodi splash logo
5. after 10 s, I can ear a 'ding' from TV
6. at this time I had to press the TV input selector, and re-select the HDMI input (that is already selected)
7. the Kodi main menu appear

### Informations
 - LE Version:  v9.2.4 Leia, Kodi v18.8
 - Hardware Platform: RPi1B with MPEG2 decoder unlocked

### Additional context

TV: Philips
Model ID: 22PFL3403D/10

Kodi resolution: 1680x1050p@60.00Hz
this is the native TV resolution when connected to a PC as seen in the manual

Bug already present in LibreELEC
v8.2.1, Kodi v17.6
v8.2.5, Kodi v17.6
v9.0.2, Kodi v18.2
and haven't found a solution.

Raspbian hasn't this issue on the same RPi1

**Comment by efa** [comment]
Kodi resolution: 1680x1050p@60.00Hz

**Comment by efa** [comment]
Kodi resolution: 1680x1050p@60.00Hz

**Comment by ChadTaljaardt** [comment]
@efa Did you ever find a workaround for this? I am having a similar issue in the issue above ^^

**Comment by efa** [comment]
as the bug happen only when the same resolution is used for both LibreElec boot and Kodi, and I want to keep the max resolution in Kodi, as a work around I forced a lower resolution in LibreElec boot

**Comment by efa** [comment]
"<LibreElecBootPartition>/config.txt"
hdmi_group=2 # DMT (Display Monitor Timings) standard used by monitors
hdmi_mode=46 # 1440x900 	60Hz 	16:10 	reduced blanking

**Comment by efa** [comment]
take note that in my case after the rainbow and boot loader menù, I can always see the LibreElec splash logo, THEN after 40 s, the TV become black. I think your case is different, maybe related to 8 GB of ram and new RPi4 model, I'm using a RPi1

**Comment by ChadTaljaardt** [comment]
Ill try test it today and will report back. Thanks for the info!

**Comment by ChadTaljaardt** [comment]
Small update @efa, i tried the nightly build of libreelec and it fixed my issue, might be worth it to you to try it too :)

**Comment by efa** [comment]
my RPi1 is a media player in holiday house, I can't reach it probably till next month, covid19 rule

**Comment by chewitt** [comment]
I'm going to close this ticket as there will be no more LE 9.2 releases to push a fix into (even if the issue was understood) and there are no plans to release RPi0/1 images for LE10 - as the completely reworked video pipeline is not suited to the low RAM size on older boards (1GB is needed).
