### ISSUE TITLE
[BUG] Build failed for Amlogic platform

### ISSUE THREAD

**Issue by numbqq** [LibreELEC/LibreELEC.tv#4530]
### Describe the bug

When linux version bump to 5.8, amlogic platform build failed due to old patch set.

### To Reproduce
```
PROJECT=Amlogic DEVICE=AMLG12 ARCH=arm ./scripts/build linux
```

**Comment by CvH** [comment]
the AML update for 5.8 is not yet pushed, volunteers welcome :)

**Comment by chewitt** [comment]
Closing after #4949 bumps everything to a current state again
