### ISSUE TITLE
Cannot correct WiFi-config (PSK) / missing possibility to remove a WiFi-config

### ISSUE THREAD

**Issue by arminfuerst** [LibreELEC/LibreELEC.tv#4534]
I observed this issue in LE9.2.3 on Raspi 3b+:
I had entered an incorrect PSK for a WPA2 WiFi and there was no way to correct the PSK through the UI. After several attempts, the UI prompted for a PSK again, but it kept trying to connect using the wrong PSK.
I solved this issue by connecting the device to a wired network, logging in to the device through SSH and editing `/storage/.cache/connman/wifi_*_managed_psk/settings`
Generally I miss a feature in the UI to remove known WiFi configurations.

**Comment by edit4ever** [comment]
I'm not seeing the same issue - when I connect with the wrong password - my the network connection times out with an error and then I can reconnect and enter the correct password.
When entering the wrong password - the cache file was created for the network I was attempting to connect to - but the password was not stored there.  Therefore on a reconnect attempt I was prompted for the password again.
There is sometimes a need to refresh the network list as it does seem to hang on my RPi every now and then - but a simple on/off of the wireless network will sort that if you don't see a refresh option in the connections.

The remove (delete) known wifi configurations does exist for connections that are valid (correct password and successful connection established).

I tested on an RPi3 running 9.2 - but if someone can recreate the error I can try to dig in again.

**Comment by arminfuerst** [comment]
I can reproduce this behavior, here are the exact steps:
1. I deleted the existing config
2. I connected to the WLAN and entered the wrong PSK
2a. In the list, the state change to "associati..." and switched back to "idle"
3. I selected the WLAN again, the menu contained "Connect" and "Refresh" (no delete, which I would need now)
4. In the menu, I selected "Connect".
4a. The connection switched to "associati..." without asking for the PSK and changed back to "idle" after some time

Is the "remove (delete) known wifi configuration" working only for connected WLANs? Probably it should be available for all cached entries, it is possible that the PSK needs to be changed on the access point and I need to delete this config? Or I need to delete a cached entry I know I will never use again.

How can I provide more details? Which details/logs/... are of interest?

**Comment by edit4ever** [comment]
The PSK is not stored in the cache unless there is a successful connection.  I'm not sure why the cache is still stored - even after selecting delete - but it does not have the PSK stored - so it should prompt again for the PSK when reconnecting.  It's possible that the system didn't completely time out before you tried to reconnect.

You can check the cache file to see if the PSK is stored in there when you enter the incorrect info - you should see all connection details except the passkey if it was not successfully connected.

I can try to see if it is possible to add the delete option for all (not sure why it wouldn't have been there from the beginning) - but this is tied to the dbus system - so its a bit messy in there.

**Comment by arminfuerst** [comment]
When I tried before, I found the invalid PSK I entered in step 2 in `/storage/.cache/connman/wifi_*_managed_psk/settings`. I did not check the file between step 1 and 2.

**Comment by edit4ever** [comment]
If you have successfully connected to that network - can you try the following:

- delete the connected network
- check that the settings cache has removed the PSK
- try to connect to the network with the wrong PSK
- check the settings cache to see if it has the PSK in it
- try to connect to the network again and see if it prompts to enter PSK
- if it does not - try to select refresh or if you can't see refresh under the network - turn wifi on and off
- try to connect to the network again and see if it prompts to enter PSK

Thanks!

**Comment by arminfuerst** [comment]
1. I deleted the network using the UI
1a. The settingsfile contains no PSK, but still details about the WLAN (I would have expected that the entry is completely deleted)
1b. There is no additional WLAN in the settings file
2. While having LAN connected, I connected to the WLAN using an invalid PSK
2a. The WLAN changed the state to "associati..." and then to "failure" (which is different to my original test, it changed back to "idle" in the original test).
2b. I got an error about already having a network connected.
2c. The settings-file now contains the invalid PSK.
3. I select the network and in the menu "Connect"
3a. I don't get a prompt for the PSK.
3b. Obviously, the connection is not possible.
4. I select the network again, and instead of selecting "Connect" from the menu, I select "Refresh"
4a. I wait until the list is redrawn
4b. The settings file now still contains the invalid PSK
5. I now select "Connect" from the menu.
5a. I am still not prompted for a PSK.

Only if I enter a PSK being too short (less than 8 characters) the PSK is not stored in the settings file.

**Comment by edit4ever** [comment]
Thanks - that gives me something to target.

If you wouldn't mind - before reconnecting - delete the settings file (if it will let you) and then try to connect again.

**Comment by arminfuerst** [comment]
I assume you mean to delete the settings file, reconnect and enter a wrong PSK and check whether the WLAN including invalid PSK is in the settings file in this case?

**Comment by edit4ever** [comment]
sorry - I mean delete and then enter correct.  I just want to make sure it's not stored anywhere else.

**Comment by arminfuerst** [comment]
This is certainly working, that's how I recovered before from this situation.

**Comment by edit4ever** [comment]
OK - I will see if I can change the system to delete the cache on unsuccessful connection.

On my system - it does not include the PSK if it fails to connect.

Thanks for the info!

**Comment by edit4ever** [comment]
I have a fix that I think will work - it's basically a workaround for the fact that the dbus doesn't clear the cache on a failed connection.

Hopefully it will get added to the Milhouse nightlies for testing.  If not - I may be able to build a version for you to test.

**Comment by arminfuerst** [comment]
If you can provide a version and some infos how to test it (and how to revert to the stable version again), I can test the fix.
I had a short look in the fix and if I understand it correctly, you remove the settings-cache completely. Wouldn't this delete all known connections (including correctly configured ones)?

**Comment by edit4ever** [comment]
I will setup a test build later today.  I assume you would prefer to stay on the LE 9.2 track instead of testing LE 10?

**Comment by arminfuerst** [comment]
I hope to be able to switch back to LE9.2.3 after the test(s), the main reason is to keep automatic updates continue to work.
If this is possible after having tested LE9.2 and LE10, I could make both tests if it makes sense.
If switching back is not possible, then I'd prefer to stay on LE9.2 - will automatic updates work when having the test build deployed?

**Comment by edit4ever** [comment]
You will be able to switch back to the automatic updates by manually loading the 9.2 back in after the test.  I can help you with that if you get stuck.  I'll let you know when the test build is ready.  Thanks.

**Comment by arminfuerst** [comment]
I have no idea what might explain this, but:
I had ideas for additional tests (basically combining connections of two WLANs one with correct, the other one with incorrect PSK, defining in different order), and when I tried to reproduce it, the error doesn't occur anymore. I'm not aware of any config change. Of course, I can still test testing versions, but I'm not sure how meaningful they are...

**Comment by edit4ever** [comment]
Thanks for the update - if you are unable to reproduce the issue we can just leave it all alone for now.

**Comment by arminfuerst** [comment]
I'm fine with that - thanks for your time!
