### ISSUE TITLE
Dd+ rpi4

### ISSUE THREAD

**Issue by JsohnAKM** [LibreELEC/LibreELEC.tv#4535]
Hi,

I've got a problem on passthrough, DD+ isn't working
It worked perfectly on 9.2.3 but since the update it's the only audio format with a problem
DTS, DD... Still worked but not the DD+
If i.downgrade.to 9.2.3 it worked again.

I used LE on a rpi4 4gb, fresh install, connect to a Denon x2500h..i have to deactivate DD+ decode in kodi parameter otherwise there's no sound on those movie

**Comment by CvH** [comment]
Closing because no issue is being reported and general questions can/should be asked in the forums.
