### ISSUE TITLE
Firefox addon ?

### ISSUE THREAD

**Issue by Qik000** [LibreELEC/LibreELEC.tv#4657]
Is there a way to get Firefox on Libreelec ? I dont like Chrome for obvious reasons and i dont want to be contributing to chrome's, and by extension, google's dominance.

**Comment by lrusak** [comment]
It's not trivial to compile a browser for an embedded distro. It's not impossible though if someone wants to put the time in.

The other option is through docker.

**Comment by chewitt** [comment]
Closing becauss this is not a bug report (what issues are for). Discussion can continue in the forums - there is at least one thread for running FF/Chrome in Docker there IIRC.
