### ISSUE TITLE
[BUG] Airplay stopped working

### ISSUE THREAD

**Issue by GoodKey** [LibreELEC/LibreELEC.tv#4676]
### Describe the bug
It is no linger possible to connect to Kodi with Airplay after the latest update. 

### To Reproduce
On iPhone 7 and 8 with the latest iOS we are no longer able to connect via Airplay.

“Unable to connect to LibreElec” popup on iOS. 

Will scan my logs and add info if anything relevant is in there

**Comment by chewitt** [comment]
Using iPhoone 8 with latest iOS and v9.2.6 i'm able to play things via Airplay, so whatever the issue is, it's local to your environment. Please take the report to the forums for further conversations, as there is no bug.
