### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by sergebenard** [LibreELEC/LibreELEC.tv#4800]
### Describe the bug

The video information does not load under specific circumstances.

I have set the Player settings to play next video automatically for TV shows, and Episodes. Once the initial video ends, or if I press `Next` from the player, the next video is loaded, and plays. For each video subsequent to the initial video, the playing video information is not loaded. I believe this is a bug because when I try to download subtitles for the show, it does not work, since there is no show information loaded.

### To Reproduce
1. Set `Settings > Player > Videos > Play Next Video Automatically` to `TV shows, Episodes`.
2. Select and play a TV episode. At any time after the video starts to play, press `Next` from the player.
3. Once the new episode is loaded, press 'Information' from the player. The episode information is not showing.

### Informations
 - LE Version: 9.2.6
 - Hardware Platform: RPi3b+

### Log file

[Log File](https://pastebin.com/pXXqehd7)

### Additional context

Thank you for a great Media Server suite!!!

**Comment by lrusak** [comment]
Looks like a Kodi bug to me and should be sent upstream.
