### ISSUE TITLE
Missing libnss3.so [BUG]

### ISSUE THREAD

**Issue by stoilovnikolai** [LibreELEC/LibreELEC.tv#4878]
### To Reproduce
1. Go to '.HBOGO europe..'
2. Play '...some video.'
3. See error

### Informations
 - LE Version: 19-nightly-20210105-1d5a0dc (RPi4.arm)
 - Hardware Platform: [e.g. RPi4]

### Log file

2021-01-06 20:59:42.862 T:1118    FATAL <general>: [script.module.inputstreamhelper] Widevine is missing the following libraries: ['libnss3.so']

**Comment by stoilovnikolai** [comment]
It was working before

**Comment by lrusak** [comment]
should be fixed by #4875
