### ISSUE TITLE
[BUG] Current RPi2 nightly seems being corrupt

### ISSUE THREAD

**Issue by Krawei** [LibreELEC/LibreELEC.tv#4903]
### Describe the bug
It seems that the last nightly (LibreELEC-RPi2.arm-9.80-nightly-20210108-2209214.tar) is broken.

### To Reproduce
1. Download the LibreELEC-RPi2.arm-9.80-nightly-20210108-2209214.tar
2. Put it into the .update folder
3. reboot
4. update
5. reboot
6. error message on bootup

### Informations
 - LE Version: LibreELEC (community): nightly-20210102-afeb291 (RPi2.arm) 
 - Hardware Platform: RPi 2

### Log file
No Logfile, but error message: "*** Error in mount_storage: mount_common: Could not mount LABEL=Storage***"

**Comment by HiassofT** [comment]
Thanks for reporting, I could reproduce the issue. Please use the older build until we have a fix for the issue (you may need to manually repair the ext4 filesystem or just do a clean install with the img.gz file)
