### ISSUE TITLE
[BUG] VideoPlayer Segmentation fault watching Sat-TV

### ISSUE THREAD

**Issue by sixpack58** [LibreELEC/LibreELEC.tv#4990]
all is here:
https://forum.libreelec.tv/thread/23323-nightly-screen-crashes-watching-sat-tv/

**Comment by sixpack58** [comment]
seems to fixed with TvHeadend 4.**3** from here:
http://build.mycvh.de/Tvh-LE9.2/

**Comment by chewitt** [comment]
I'm closing the ticket as a new TVH 4.3 add-on has been merged and will appear in the LE 10 repo sometime this week once an add-on build run takes place. Thanks.

**Comment by heitbaum** [comment]
#5188
