### ISSUE TITLE
HTTPS in libmicrohttpd

### ISSUE THREAD

**Issue by francoismelchior** [LibreELEC/LibreELEC.tv#5136]
Hello,
is there any reason https://github.com/LibreELEC/LibreELEC.tv/blob/master/packages/web/libmicrohttpd/package.mk has "--disable-https"? Might that be the only thing preventing the Kodi webserver to work with HTTPS?

**Comment by lrusak** [comment]
well, to provide HTTPS you also need to provide certs.

**Comment by francoismelchior** [comment]
Yes indeed I wanted to mean in the LibreELEC software!
