### ISSUE TITLE
[Issue]Some YouTube videos are not playing

### ISSUE THREAD

**Issue by sunilpallikkara** [LibreELEC/LibreELEC.tv#5186]
I am using KODI on  RaspberryPi 3+ and configured YouTube addon and it was working fine till last week. Now some youtube Videos are not playing by giving YouTube error.
LibreElec Version: 9.2.6
KODI: 18.9.

Advance Thanks for help.

Sunil

**Comment by chewitt** [comment]
> Advance Thanks for help.

Ask Q's in the Kodi forum support thread for the YouTube add-on, or the LE forum. This is a bug tracker so closing the ticket.
