### ISSUE TITLE
[BUGFIX] Incorrect video decoding on Asrock Gemini Lake M-ITX board of 10-bit HEVC/h.265 videos

### ISSUE THREAD

**Issue by Klojum** [LibreELEC/LibreELEC.tv#5195]
### Describe the bug

Incorrect video decoding on Asrock Gemini Lake M-ITX board of 10-bit HEVC/h.265 videos

### To Reproduce
1. Play any 10-bit HEVC video
2. Incorrect colors and display of video
3. Green is the main color, and the display is cut into 2 separate sides, one of which being totally filled with the color green.

### Informations
 - LE Version: v9.95.1+ (also possibly in earlier versions)
 - Hardware Platform: Generic Intel x86-64

### Log file

N/A

### Additional context

Problem fixed by adding the file **/storage/.config/kodi.conf** with the following content:
LIBVA_DRIVER_NAME="i965"

Reboot LibreELEC or restart Kodi via SSH.

**Comment by heitbaum** [comment]
Closing as stale, as LE11 and LE12 have been updated to gbm, and mesa has been updated. If still an issue - please reopen with updated info.
