### ISSUE TITLE
[BUG] Firewall "Home" rules does not let LSIO docker addons recieve packets

### ISSUE THREAD

**Issue by Salokyn** [LibreELEC/LibreELEC.tv#5209]
### Describe the bug
I installed several addons (docker containers) from LinuxServer.io repo.
When firewall is activated with "home" rules. Those containers wich are connected to a dedicatated "lsio" docker network cannot connect to the internet.

### To Reproduce
1. Install an addon from LinuxServer.io repo.
2. Activate firewall
3. Try to connect to internet from this container. ex: `docker container exec resilio-sync curl www.free.fr`

### Informations
 - LE Version: 9.2.6
 - Hardware Platform: RPi4

### Log file
Cannot use `-j LOG` on iptables rules :sob: 

### Additional context
Adding the following to `/etc/iptables/home.v4` should fix the problem:
```iptables
-A private-subnets -s 10.0.0.0/8 -i br+ -m conntrack --ctstate NEW -j ACCEPT
-A private-subnets -s 172.16.0.0/12 -i br+ -m conntrack --ctstate NEW -j ACCEPT
-A private-subnets -s 192.168.0.0/16 -i br+ -m conntrack --ctstate NEW -j ACCEPT
```

**Comment by wolfsolver** [comment]
same issue, but unable to add to iptables. Try to add to 
```
LibreELEC:~/.config/iptables # cat rules.v4
-A private-subnets -s 10.0.0.0/8 -i br+ -m conntrack --ctstate NEW -j ACCEPT
-A private-subnets -s 172.16.0.0/12 -i br+ -m conntrack --ctstate NEW -j ACCEPT
-A private-subnets -s 192.168.0.0/16 -i br+ -m conntrack --ctstate NEW -j ACCEPT
```
without any result. also nslookup not working.
