### ISSUE TITLE
[BUG] Raspberry Pi 2/3: 3.5mm audio jack (headphone jack) not working 

### ISSUE THREAD

**Issue by BugDeliverer** [LibreELEC/LibreELEC.tv#5225]
After updating LE 10 on RPi2 to latest nightly 3.5mm audio jack stopped working. Also clean install and switching to a RPi3 did not solve the issue.

### To Reproduce
1. Clean install or update to LE 10 nightly
2. Got to System -> Audio
3. Only HDMI output is available

### Informations
 - LE Version: all available 10.0 nightly (02/28 to 03/07) 
 - Hardware Platform: Reproduced on RPi2 and RPi3

### Log file
https://pastebin.com/VLMdYx22

### Additional context
-

**Comment by HiassofT** [comment]
Please use our forums for support questions.

You have to add "dtparam=audio=on" to config.txt if you want to use analog audio output from the headphone jack.
