### ISSUE TITLE
[BUG] "Sync playback to display" setting disappeared on LibreElec 10.0

### ISSUE THREAD

**Issue by ironman771** [LibreELEC/LibreELEC.tv#5250]
### Describe the bug

In Settings -> Player -> Videos -> "Sync playback to display" setting disappeared !
This setting is needed to increase the playback speed more than 1x with audio (tempoup and tempodown kodi functions).
This is one of the most important functions for me!
I believe that the problem may be in the Kodi package and precisely in this file:
xbmc/windowing/gbm/WinSystemGbm.cpp

### To Reproduce
1. Go to Settings -> Player -> Videos -> "Sync playback to display" setting is gone.

### Informations
 - LE Version: 9.95.1 (10.0 beta1)
 - Hardware Platform: RPi4

**Comment by lrusak** [comment]
Please use the forum for support. Thanks!
