### ISSUE TITLE
[BUG] When a requests.Session().post is done which returns a response 204 and on that response a response.json() is done then instead of an exception JSONDecodeError an error IndexError: string index out of range is given 

### ISSUE THREAD

**Issue by peno64** [LibreELEC/LibreELEC.tv#5254]
### Describe the bug

On a raspberry pi4 with the latest libreelec, kodi 19, when a requests.Session().post is done which returns a response 204 and on that response a response.json() is done then instead of an exception JSONDecodeError an error IndexError: string index out of range is given

Note that the same code with kodi 19 on windows does give the expected JSONDecodeError and also with kodi 18.9 with libreelec the expected JSONDecodeError is given.

Unfortunately I am not a good enough python developer to provide and example but it should not be hard to create an example that returns this response.

### Informations
 - LE Version: 9.95.1  1.0 kernel linux 5.10.17
 - Hardware Platform: RPi4

**Comment by lrusak** [comment]
Please report upstream
