### ISSUE TITLE
[BUG] blank screen

### ISSUE THREAD

**Issue by donbrew1** [LibreELEC/LibreELEC.tv#5263]
This is a long standing problem.  When installing a fresh LE (9 & 10)/Kodi (18.3 to 19) on a RPI4 with an old TV (without CEC, no overscan just "aspect") the screen goes blank after the LE splash (sometimes after the RPI splash) and seems to crash.  I think it has been fixed in Raspbian/Raspberry Pi OS.  My HDMI cable is good (works with Pi3B).  Ubuntu 20.04  works nicely out of the box, I have not tried to put Kodi on Ubuntu. 

Seems to be either CEC or overscan is the problem.  My TV has no CEC and I must do the video calibration in Kodi to adjust the screen because the TV's aspect controls don't fix it.

Seems to be a big problem that nobody will admit.  There is a hard to find chapter in a wiki about how to troubleshoot blank screen that basically presents this solution.  Sorry, I came across it on accident and don't recall the exact particulars.

There are may instances across the internet of users throwing there brand new Pi4s away because of this, I almost did.  Just GoOgle "libreelec black screen rpi4".

I posted this solution for my TV, a 2006 Polaroid 42 inch last year.  It gets you a picture, at least, then you can tweak.

```
gpu_mem=320
force_turbo=0
hdmi_ignore_edid=0xa5000080
disable_overscan=1
framebuffer_width=1920
framebuffer_height=1080
hdmi_force_hotplug=1
hdmi_group=1
hdmi_mode=16
hdmi_ignore_cec=1 
dtparam=audio=on
dtoverlay=vc4-fkms-v3d
max_framebuffers=2

debug log file config.txt that works [](https://pastebin.com/sbGEppQB)
debug log file config.txt blank screen [](https://pastebin.com/C7F18Av1)

**Comment by HiassofT** [comment]
Stick to your forum thread https://forum.libreelec.tv/thread/23684-getting-log-files/
