### ISSUE TITLE
[BUG] cant change gpu_mem & aktivate 4k 60hz 

### ISSUE THREAD

**Issue by EnricoSanchez** [LibreELEC/LibreELEC.tv#5281]
### Describe the bug
when i change gpu mem in config.txt kodi starts with black screen but reacts to remote

when i add hdmi_enable_4kp60=1 i cant chose it at kodi setting menu

with libreelec 9 both works 

### To Reproduce
1. change gpu_mem to 512 and add hdmi_enable_4kp60=1
2. start
3. black screen at memory change but i can use remote to reboot 
4. when 4k 60 added to config.txt it is not available at kodi setting

 thanks for help and sorry about my bad english

### Informations
 - LE Version: 9.95.1
 - Hardware Platform: RPI4

**Comment by HiassofT** [comment]
Don't change gpu_mem, this is not needed and will just cause the effects you described.

4kp60 isn't implemented yet in the driver, this will follow at a later point, so don't use hdmi_enable_4kp60=1 yet either.
