### ISSUE TITLE
[BUG]Download links LibreElec not working

### ISSUE THREAD

**Issue by NickFatbob** [LibreELEC/LibreELEC.tv#5286]
### Describe the bug
I am not able to download the “LibreELEC USB-SD Creator” app from https://libreelec.tv/downloads_new/
None of the links are working. Am I doing something wrong?  
I am a newbie.

### To Reproduce
2. Play '....'
3. See error

### Informations
 - LE Version: [e.g. 9.2.1]
 - Hardware Platform: [e.g. RPi3]

**Comment by heitbaum** [comment]
here are the links from the https://libreelec.tv/downloads_new/.

http://releases.libreelec.tv/LibreELEC.USB-SD.Creator.Win32.exe
http://releases.libreelec.tv/LibreELEC.USB-SD.Creator.Linux-32bit.bin
http://releases.libreelec.tv/LibreELEC.USB-SD.Creator.Linux-64bit.bin
http://releases.libreelec.tv/LibreELEC.USB-SD.Creator.macOS.dmg

Please use the forums for support.

**Comment by CvH** [comment]
Main problem is chrome/chromium that are now blocking downloads with a lot known extensions like .zip, .exe etc ... .
You need "right click" -> "save link as" to workaround.

**Comment by NickFatbob** [comment]
Thanks for your reply, but unfortunately those links are not working (at my pc)

**Comment by NickFatbob** [comment]
CvH: thank you. Problem solved. Google is going crazy making decisions like that.
