### ISSUE TITLE
[BUG] LE settings addon causes crashes when switching profiles

### ISSUE THREAD

**Issue by HiassofT** [LibreELEC/LibreELEC.tv#5303]
### Describe the bug

When switching profiles, eg from master user to a separate profile, kodi crashes if LE settings addon is included in system image.

The issue was originally reported on the forum https://forum.libreelec.tv/thread/23657-le-10-0b1-crash-after-profile-change/

### To Reproduce
1. Clean LE installation, accept defaults in wizard
2. Create one (or two) profiles in settings->profiles, accept defaults, enable "Show login screen on startup"
3. reboot LE
4. select master profile in login screen
5. log out of master profile
6. select first created profile in login screen
7. kodi crashes

### Informations
 - LE Version: LE 10b1, master
 - Hardware Platform: RPi4, forum users also reported Generic

### Log file
Kodi crash log: http://ix.io/2Vrs

### Additional context
The crash log points to  python's _asyncio.so lib which indicates the crash is probably caused by the LE settings addon.

Building an image without LE settings addon results in working profile switching without crashes.

Log file from switching between master and both test profiles back and forth several times: http://ix.io/2Vrv

**Comment by lrusak** [comment]
Can you enable LE settings add-on debugging and post another log please?

**Comment by HiassofT** [comment]
Here's a log with DEBUG=1 in kodi.conf: http://ix.io/2Vt3

**Comment by lrusak** [comment]
it's a long shot but can you test this patch? https://termbin.com/y454

**Comment by HiassofT** [comment]
the patch didn't help - kodi is still crashing http://ix.io/2VwX

**Comment by lrusak** [comment]
Does it crash if you disable/enable the add-on?

**Comment by HiassofT** [comment]
enabling/disabling isn't possible in kodi, probably because it's flagged as a system addon

![screenshot00000](https://user-images.githubusercontent.com/3920953/114234597-486e0c00-997f-11eb-9f32-679ba1f172ad.png)

**Comment by antonlacon** [comment]
If I disable Bluetooth (Settings -> Services), I can switch profiles at will.

**Comment by NeverEatYellowSwissSnow** [comment]
> 
> 
> If I disable Bluetooth (Settings -> Services), I can switch profiles at will.

Not in my case. Still crashing.

**Comment by NeverEatYellowSwissSnow** [comment]
Still crashing on LE 10b3, x86 generic.

**Comment by romanvm** [comment]
Multiple profiles support in Kodi is broken for some time and should be removed if someone finds time to do it.

**Comment by NeverEatYellowSwissSnow** [comment]
> 
> 
> Multiple profiles support in Kodi is broken for some time and should be removed if someone finds time to do it.

What do you mean it's broken in Kodi? I have several Kodi 19.1 installations which are all running fine with multiple profiles. It's just crashing in LibreELEC, not in Kodi. Don't get me wrong but just because the code is bad doesn't mean it's broken?
It would be too sad if multiple profiles were removed, this is the main reason I am using Kodi/LibreELEC because that way I can manage all of my familiy members individually and keep kids away from things that do not belong to them.

**Comment by HiassofT** [comment]
FYI: latest nightly is still crashing with the same _asyncio.so backtrace http://ix.io/3utf

**Comment by CvH** [comment]
just a warning, looks like nobody is looking into the issue so LE10 final will have this broken

**Comment by jfilaa** [comment]
Raspberry Pi TV HAT not working. RPi4 TV HAT is not detected.

**Comment by HiassofT** [comment]
Looks like we just forgot to close the issue. Tested with LE master, profile logoff/logon works fine
