### ISSUE TITLE
[BUG] Black screen when using analog output

### ISSUE THREAD

**Issue by Hiki1** [LibreELEC/LibreELEC.tv#5335]
### Describe the bug
Black screen occurs during boot, when using composite output of the Raspberry Pi

### To Reproduce
1. Fresh installation of 9.95.2
2. Edit the config.txt and set **enable_tvout=1** there
3. Connect the RPi to a CRT TV via analog output - jack to composite cable is required
4. Initially the colored box appear like [here](![image](https://user-images.githubusercontent.com/20788490/115777576-c4bc1280-a3b5-11eb-9661-183dd57807ad.png)) for short while
5. Black screen occurs and stays like that

### Informations
 - LE Version: 9.95.2
 - Hardware Platform: RPi4

### Additional context
Jack to RCA cable looks like [that](![image](https://user-images.githubusercontent.com/20788490/115777976-3eec9700-a3b6-11eb-902f-227741cd8e6e.png)).

**Comment by HiassofT** [comment]
Initial support for tvout has landed in RPi kernel just yesterday https://github.com/raspberrypi/linux/pull/4240

These changes will be included in future LE versions (but they came too late for beta2)

**Comment by Hiki1** [comment]
Sounds great! Thanks for the info!

**Comment by Hiki1** [comment]
I've retested this issue on a 9.95.3 and unfortunately it still does occur.

**Comment by HiassofT** [comment]
9.95.3 uses the same kernel as 9.95.2 - we had to revert the kernel bump as it caused issues and we are still waiting for a fix.

**Comment by heitbaum** [comment]
@Hiki1 closing this ticket. If you are still having issue with LE10/11 - please reopen this bug.
