### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by peppenamir** [LibreELEC/LibreELEC.tv#5352]
### Describe the bug
bad audio with the 3.5mm Jack

### To Reproduce
I modified the config.txt file with the parameter
dtparam = audio = on 

but the audio is bad

### Informations
 - LE Version: [e.g. 9.95.2]
 - Hardware Platform: [RPi4]

**Comment by lrusak** [comment]
That's just the way it is.

**Comment by peppenamir** [comment]
no fix?

**Comment by chewitt** [comment]
RPi4 does not have great analogue audio out, unless you add an external "DAC" board. So there is no bug to fix, hence the ticket is closed.
