### ISSUE TITLE
[BUG] Issues with Udemy, Arte Mediathek and LibreELEC configuration on Matrix

### ISSUE THREAD

**Issue by coldspark29** [LibreELEC/LibreELEC.tv#5355]
### Describe the bug
I have issues with Udemy video playback, arte Mediathek playback and sometimes the LibreELEC configuration plugin doesn't start. Udemy used to work before and I actually need to watch some things. Is there a know bug with Python 3 or something? I already tried wiping the home directory to get rid of all the settings, but with no success.

I btw did frankly not understand why the update was available in the configuration although it is still in beta phase. A lot of things broke and I also couldn't go back to Leia, because nothing would work anymore. A warning about the state of Matrix in the updater would have been very nice!

### To Reproduce
1. Install Udemy or arte Mediathek
2. Play a video
3. See error message

### Informations
 - LE Version: 9.95.2
 - Hardware Platform: Pi4

### Log file
[http://ix.io/3lOU](http://ix.io/3lOU)
[http://ix.io/3lOW](http://ix.io/3lOW)

**Comment by lrusak** [comment]
Please use the forum for support thanks!
