### ISSUE TITLE
[BUG] Enable autoupdate of bootloader and via usb on every reboot

### ISSUE THREAD

**Issue by MartinX3** [LibreELEC/LibreELEC.tv#5366]
### Describe the bug
Currently i can update the EEPROM-Bootloader and VIA USB 3.0 Firmware once on a reboot and need to reactivate each time.
I administrate the libre elec installations of family member and would need to manually search for updates and upgrade them everytime at their location.

I would like to have an option to autoupdate the stuff on every reboot instead only once.
The raspianOS does it automatically on every reboot.
And since have the auto updater of LE it would be nice to upgrade the other stuff on every automatical LE reboot as well.

### To Reproduce
1. Use the updater settings

### Informations
 - LE Version: 9.95.2
 - Hardware Platform: RPi4

**Comment by HiassofT** [comment]
Please use the forum for feature request, this tracker is only for reporting bugs.

Putting `rpi-eeprom-update -a` into `.config/autostart.sh` should to what you want.

**Comment by MartinX3** [comment]
@HiassofT 
Thank you for your help
I didn't know that
Could you put this information into the README.md and adding a issue tracker template named "Feature Request" containing big letters, that we should ask such stuff in the forum?
That would avoid wrong tickets like mine in the future. :)
