### ISSUE TITLE
Bump inputstream adaptive to version 2.6.15

### ISSUE THREAD

**Issue by mmacchia** [LibreELEC/LibreELEC.tv#5380]
Hi! The library inputstream adaptive [repository here|https://github.com/xbmc/inputstream.adaptive] has been updated to version 2.6.15.
Would it be possible to reflect this change in the official Libreelec repository?

Otherwise, how is it possible to compile it from source on Libreelec?
Thank you!

**Comment by CvH** [comment]
https://github.com/LibreELEC/LibreELEC.tv/pull/5381

**Comment by mmacchia** [comment]
Thank you for the link to the PR! I tried forcing the update of the Libreelec repository, but the new version still does not show up. What is the suggested way to find the latest merged changes in Libreelec?
I am running the latest beta version, 9.95.2, and the Libreelec repository is version 9.80.11.
