### ISSUE TITLE
Audio playback sporadic w/ RPi4 + Allo Digione HAT with LibreELEC 9.95.3 - Kodi Music Server

### ISSUE THREAD

**Issue by BilSheckler** [LibreELEC/LibreELEC.tv#5387]
The LibreELEC log file is at http://ix.io/3nvQ
The Kodi logfile kept failing to upload because of size. (I usually have ~24K .flac files on a Samsung T5 SSD on a Sabrent USB adapter and this worked very well with the original RPi4 and LibreELEC 9.2.0.) So I copied one album onto a USB stick in a simple effort to reduce logfile size, and rebooted. It played every song off the USB sting with nary a dropout.
What the Beta software was producing wasn't dropouts (which I define as random sound breaks of a fraction of a second).
At first I thought that it was muting the sound and the song was progressing, but after a couple more, I realized that it was usually just pausing play. The breaks last for ~5-20 seconds. Sometimes the silence happens, and another song starts playing.
The RPi screen does not give any indication that anything is amiss. The DAC does not indicate loss of signal, and continues to display the correct data type and rate.
With the first gen RPi4 and LibreELEC 9.2.0 I was getting about one dropout an hour.
With the latest RPi4 and LibreELEC 9.95.3 BETA I am getting these events about once a song.
I was surprised when I could not reproduce the problem with a fraction of a % of the music data, but perhaps that's useful.
It is a 1TB drive with 603 MB used. Virtually all .flacs w/ some .jpg's.
Thank You very much for your help !
Best Regards,
Bil

**Comment by HiassofT** [comment]
You are using a problematic USB SATA adapter which causes frequent disconnects. See also this sticky on the RPi forums https://www.raspberrypi.org/forums/viewtopic.php?t=245931

Adding `usb-storage.quirks=152d:1561:u` to the end of /flash/cmdline.txt should fix this
