### ISSUE TITLE
[BUG] LibreELEC Master Build Error with U-boot on RK3399

### ISSUE THREAD

**Issue by mo123** [LibreELEC/LibreELEC.tv#5440]
### To Reproduce
1. Build any RK3399 image

### Informations
 - LE Version: [e.g. 9.2.1] Master
 - Hardware Platform: [e.g. RPi3] RK3399

### Log file

https://pastebin.com/i9tMXqE1

**Comment by lrusak** [comment]
After a quick look it almost look like something is picked up from your host system.

**Comment by jernejsk** [comment]
It would be helpful if you would tell us which host distro you're using. Anyway, remove libfdt and related packages from your system. I had this kind of problems on Arch in the past.

**Comment by mo123** [comment]
Ubuntu 20.04
I removed libfdt-dev package and now the build process continues.
Must have been an Ubuntu update because yesterday everything was still working fine.

Thanks
