### ISSUE TITLE
restore backup doesnt work

### ISSUE THREAD

**Issue by s0i37** [LibreELEC/LibreELEC.tv#5450]
### Describe the bug
restore backup doesnt work

### To Reproduce
1. Go to 'create backup'
2. Play 'restore backup'
3. ~/.kodi/userdata/addon_data/ are empty after restore

### Informations
 - LE Version: LibreELEC (official): 9.2.6 (RPi4.arm)
 - Hardware Platform: from RPi3B+ to RPi3

**Comment by antonlacon** [comment]
Does `~/.kodi/userdata/addon_data/` have contents in the backup tar file?

**Comment by heitbaum** [comment]
@s0i37 - just following up on this ticket. How did you go?

**Comment by heitbaum** [comment]
Closing. Please let us know any further issue and we can reopen if needed.

**Comment by DoctorOctagonapus** [comment]
If you're reading this and you're trying to restore a backup to downgrade from 10.0.0 to 9.x, don't bother. It won't work and you'll end up bricking your system. Copy the backup file off to an external disk, wipe and reinstall with the old version and restore the backup to that.
