### ISSUE TITLE
Wireguard does not work with DDNS

### ISSUE THREAD

**Issue by angrynerd** [LibreELEC/LibreELEC.tv#5472]
### Describe the bug
Wireguard via connman does not work with ddns domain.

### To Reproduce
1. set the host as a domain.
2. does not connect.
3. set host to the public ip. 
4. does connect.

### Informations
 - LE Version: 9.2.6
 - Hardware Platform: RPI3b+

### Additional context
DDNS is very important personally as my ip address is not static with my isp.

**Comment by lrusak** [comment]
Can you resolve the ddns domain with dig or curl or similar?

**Comment by mglae** [comment]
There is some discussion on the forum:
https://forum.libreelec.tv/thread/17965-add-wireguard-support/
https://forum.libreelec.tv/thread/21603-wireguard-server-as-hostname-issue/
https://forum.libreelec.tv/thread/22007-wireguard-troubleshooting-no-reply/

Seem to be a connman limitation.

**Comment by angrynerd** [comment]
@lrusak Yes I am amble to resolve the domain. @mglae I have read through the first one and tried to use the scripts from there to solve the issue but I dont understand them completely so im not sure how to fit them to my needs. The script in the second link seems like while its more files involved it should be simpler to understand. Im going to try that and then report back.

**Comment by angrynerd** [comment]
Ok can confirm that the script from the second link works flawlessly! THank you for you assistance. To anyone else who hits this wall that script is largely the easiest to understand.
