### ISSUE TITLE
Subtitles sometimes don't display [BUG]

### ISSUE THREAD

**Issue by PrzemekSkw** [LibreELEC/LibreELEC.tv#5477]
### Describe the bug

I have Libre Elec installed on Rpi4. I set Polish subtitles everywhere in settings. 
Some movies and series have already subtitles involved like series/movies from netflix. Kodi show me polish subtitles are present and there's checked box for display subtitles but when I click play it don't display them. I must click download subtitles and then they work. When I resume the same movie/episode I have to download subtitles again because Kodi don't display them.

### Informations
 - LE Version: 9.2.6
 - Hardware Platform: [RPi4b]
- Kodi 18.9
### Log file
https://paste.gnome.org/pv44mfrmz
### Additional context
I use Emby for Kodi addon and I connect to my own Emby server. I use it before (in earlier kodi versions - openelec, libreelec, osmc with Rpi2, Rpi3,Rpi4) and there was no problem with that. I have installed before pure kodi on Debian on HP Intel 64Bit MiniPC and also was that problem with subtitles.

Regards,
Przemek

**Comment by lrusak** [comment]
Please report to the Kodi forums about the issue and if it's a confirmed bug please make an issue on the Kodi GitHub issue tracker. Thanks.
