### ISSUE TITLE
[BUG] Can't enable 4k60 rpi4

### ISSUE THREAD

**Issue by rjousse18** [LibreELEC/LibreELEC.tv#5495]
### Describe the bug
I can't enable 4k60 on my pi4 2gb. I added the option hdmi_enable_4kp60=1 on config.txt but when I start the pi, I have a black screen and can't interact with kodi. Why ? It's a problem for because if I choose 4k24, I can't play video >25fps.

### To Reproduce
1. Put hdmi_enable_4kp60=1 on config.txt
2. Run pi4

### Informations
 - LE Version: 9.95.5
 - Hardware Platform: RPi4 2gb

**Comment by chewitt** [comment]
Please use the forums for user support, thanks.
