### ISSUE TITLE
[BUG] Outdated NOOBS packages

### ISSUE THREAD

**Issue by isantolin** [LibreELEC/LibreELEC.tv#5500]
### Describe the bug
The latest version for LibreELEC is 9.2.8 but Raspberry NOOBS downloads 9.2.6
Anyone can update Packages for Noobs? http://releases.libreelec.tv/noobs/LibreELEC_RPi2/System.tar.xz, http://releases.libreelec.tv/noobs/LibreELEC_RPi2/Storage.tar.xz

### To Reproduce
1. Go to Raspberry NOOBS LibreELEC Install
2. Installed version will be 9.2.6, not 9.2.8

### Informations
 - LE Version: Latest NOOBS
 - Hardware Platform: RPi3

**Comment by CvH** [comment]
this is intended, at the moment at least
9.2.7 and 9.2.8 just include experimental fixes targeted for the usage of widevine, nothing else
in the meantime you can just update to the latest version if needed

**Comment by chewitt** [comment]
Closing as RPi/RPi2 are now running 9.2.8 and RPi4 is updated to 10.0.0
