### ISSUE TITLE
[BUG] RPi2 Won't boot past rainbow screen

### ISSUE THREAD

**Issue by jclemons7** [LibreELEC/LibreELEC.tv#5512]
RPi2 Won't boot past rainbow screen with LibreELEC-RPi2.arm-9.2.8.img.gz 

### To Reproduce
Load LibreELEC-RPi2.arm-9.2.8.img.gz on SD card.  Boot.

### Informations
 - 9.2.8
 - RPi2
 - 8GB SD card

### Log file
Can't get log file, won't boot

### Additional context
RPi2 boots fine with other OS's with exact same physical configuration.

**Comment by lrusak** [comment]
How did you flash the SD card?

**Comment by jclemons7** [comment]
I used LibreELEC.USB-SD.Creator.Linux-64bit.bin, but now I'm trying Imager, which seems to have an older version of Elec.. more to come on that I guess.

**Comment by jclemons7** [comment]
Hmmm.. same effect with Imager.

**Comment by antonbo** [comment]
Hi,
I have same issue. But in my case the problem appears with RPi2 B+ v1.2. Older version v1.1 (which uses another chip) works fine with same SD card and power supply. Seems like a problem is in Linux kernel. I've tried to put kernel.img from Raspbian Bullseye and it started.

**Comment by heitbaum** [comment]
Closing as a stale ticket. Please reopen with updated info, or use forum.
