### ISSUE TITLE
ts_env.sh-sample has an error that prevents eGalax touchscreens from being calibratable

### ISSUE THREAD

**Issue by lademeister** [LibreELEC/LibreELEC.tv#5520]
It took me some days till I found the problem, and I guess a lot of other people out there have the same problem.
I found the solution and the root cause why Libreelec + Kodi + eGalax touchscreen is not calibratable (axes are swapped and touchscreen calibration tool in Kodi (5-Point calibration) does not work).
The reason is that ts_env.sh-sample and the ts_env.sh derived from that has an error: it tries to match the device identifier, but at least in my case the command evtest shows two identical eGalax devices, only that one has the word „pen“ behind it:

eGalax Inc. USB TouchController Pen 
eGalax Inc. USB TouchController

The script detection stops on a full match, which unfortunately is the one with „Pen“ behind it as it’s always listed first.
That is why „touchscreen“ app in Kodi does not work and cursor x-axis and y-axis are inverted for the eGalax touchscreen and cannot be calibrated.

Solution: in ts_env.sh-sample the line
TSLIB_TSDEVICE=$(echo 999 | evtest 2>&1 >/dev/null | awk -F':' -v TS_NAME="$TOUCHSCREEN_NAME" '$0 ~ TS_NAME {print $1; exit}')

needs to be modified by adding a $-sign after TOUCHSCREEN_NAME like this:

TSLIB_TSDEVICE=$(echo 999 | evtest 2>&1 >/dev/null | awk -F':' -v TS_NAME="$TOUCHSCREEN_NAME$" '$0 ~ TS_NAME {print $1; exit}')

now the script only triggers the exact match (AND nothing behind, like „Pen“).

For those who have the same problem and  find this issue description  I’ll guide you to the full solution here as well, as nowhere on the internet anyone seems to put references.

to get via ssh onto your libreelec/Kodi setup:
from a computer on the same network open a Linux console and type
ssh root@YOURIP
password will be asked, it is libreelec
Replace YOURIP with the actual IP address of the libreelec machine, you might log into your FRITZ!Box or Router to find it

Make sure ssh is enabled in Kodi settings
Also make sure „disable ssh password“ is NOT (!!) checked.

as soon as you are logged in via ssh:

file location: /storage/.kodi/userdata/addon_data/service.touchscreen/ts_env.sh-sample

you can edit that file using nano:

nano /storage/.kodi/userdata/addon_data/service.touchscreen/ts_env.sh-sample

here you need to add the $-Sign as described above, then hit ctrl-o and enter to save and ctrl-x to leave nano

then,
following those instructions 
https://forum.libreelec.tv/thread/15466-touchscreen-intel-x64-problem/#codeLine_41_com_woltlab_wbb_post_117185_8cecd7
everything works like a charm.

basically what the link describes is to copy the sample files to the right paths and to rename them (do that after the modification with the added $-sign that I described above):

cp /storage/.kodi/userdata/addon_data/service.touchscreen/ts_env.sh-sample /storage/.kodi/userdata/addon_data/service.touchscreen/ts_env.sh
cp /storage/.kodi/userdata/addon_data/service.touchscreen/ts.conf-generic /storage/.kodi/userdata/addon_data/service.touchscreen/ts.conf
cp /storage/.kodi/userdata/addon_data/service.touchscreen/ts.conf-generic /storage/.kodi/addons/service.touchscreen/ts.conf
cp /storage/.kodi/userdata/addon_data/service.touchscreen/ts_env.sh /storage/.kodi/addons/service.touchscreen/ts_env.sh

now you call 

ts_env.sh
(without any path)

This is basically is the copy of the modified ts_env.sh-sample file

Then you type

reboot 

After reboot your touchscreen app in Kodi will be able to do the 5-point calibration, as it now uses the right device.
It may be that some eGalax touchscreens don’t have this problem, but as it took me days to search all the forums I allowed myself to post the full solution here as well.

**Comment by lrusak** [comment]
Why not just submit a PR with the fix?
