### ISSUE TITLE
Add RK322x suport on LibreElec 10.0.0

### ISSUE THREAD

**Issue by DavidBrazSan** [LibreELEC/LibreELEC.tv#5556]
I have a TV box with chip Rk3229 and wanted this version with the latest kodi. I know you have a fork that supports this chip but has not been updated.

**Comment by jernejsk** [comment]
Feature requests are not issues, use forum for that.

Anyway, adding support for new SoCs brings a lot more effort than adding few lines of code and some patches. Somebody has to maintain that. You can encourage original RK3229 fork author to do that or you can step in and do that.

**Comment by DavidBrazSan** [comment]
Thanks for letting me know and sorry for making such issues.
