### ISSUE TITLE
Librespot playback stutters at first start on Raspberry Pi 4

### ISSUE THREAD

**Issue by gumida** [LibreELEC/LibreELEC.tv#5557]
### Describe the bug
_(This is very similar to #5328 but not completely the same. I hope a separate issue is appropriated)_ 

The first song played via librespot is out of rhythm at the beginning. In the first few seconds it starts to stutter, then getting little bit to fast, then a little bit so slow and normalizes after 10 seconds.
It's only the first song in a session - everything afterwards is alright.

### To Reproduce
1. Install Librespot on LibreELEC running on Raspberry Pi 4
2. Connect to Librespot from Spotify and start playing something (I can recommend a "200 BPM metronome" song :smile:)
3. The first 10 seconds of the first song played sounds "weird": out of rhythm and also some noises are distorted.

### Informations
 - LE Version: 9.97.1
 - Hardware Platform: Raspberry Pi 4 + HiFiBerry DAC+

### Log file
http://sprunge.us/TOmRQL

### Additional context
The some hardware combination was working fine with LibreELEC 9.2 before.

I've tried to record the speaker output and visualize the recorded audio file: 
- A x BPM metronome sound was played
- So each beat must have exactly the same interval.
- I've split the beats into individual lines so that, in theory, they should all be the same length:
- ![beat](https://user-images.githubusercontent.com/5578303/129939903-c41b6b4a-44ce-4c88-b467-c2ea559193c1.png)
- It's not cut out perfectly, but I hope you can see the problem.
- Everything that comes after that is the same length again.

**Comment by heitbaum** [comment]
@gumida - still an issue with LE10/11? Please reopen with updated logs if still an issue.
