### ISSUE TITLE
service.libreelec.settings Turkish translation is 100%. Please sync

### ISSUE THREAD

**Issue by queeup** [LibreELEC/LibreELEC.tv#5590]
### Describe the bug

Is it possible to pull corrections and new translates from ~~transifex~~ kodi weblate to github, and then release new version of the service.libreelec.settings addon?

Github Turkish language file is a little bit old.

### To Reproduce
N/A

### Informations
 - LE Version: 10.0.0
 - Hardware Platform: RPi4

### Log file

N/A

### Additional context

~~https://www.transifex.com/libreelec/service_libreelec_settings/language/tr_TR/~~
https://kodi.weblate.cloud/projects/kodi-add-ons-services/service-libreelec-settings/tr_tr/

**Comment by CvH** [comment]
should be fixed now
