### ISSUE TITLE
Enable auto-update to 9.2.8?

### ISSUE THREAD

**Issue by matthuisman** [LibreELEC/LibreELEC.tv#5596]
Hi team,

Would you be able to consider enabling the auto update to 9.2.8?
The old widevine version is starting to get revoked (many addons already broken)
and hopefully by now you may know it's stable and safe?

It may just save us all a bit of time if users system gets auto updated and we don't need to explain the manual process

Thanks,

Matt

**Comment by matthuisman** [comment]
@CvH @chewitt
any thoughts on above?
enabling auto-update from below 9.2.8 to 9.2.8 would be great.

**Comment by chewitt** [comment]
@matthuisman I've enabled auto-update to LE 9.2.8 for RPi2, RPi4 and Slice3 (the only releases we built 9.2.8 for)

**Comment by matthuisman** [comment]
thats awesome!
thank you :)
