### ISSUE TITLE
Enabling a numeric Master Lock has unintended side-effects [BUG]

### ISSUE THREAD

**Issue by CursedDevelopment** [LibreELEC/LibreELEC.tv#5634]
### Describe the bug
Enabling a numeric Master lock (under Settings / Interface) with all its lock preferences disabled causes addons to require a lock password which is not equivalent with the configured numeric lock.
Running an addon will repeat prompting for the number until after retries are used up one is permanently presented with an "Access denied / Password retry limit exceeded" dialog.

I don't think that addons should be restricted to begin with, but if they are, at least the correct password should be accepted.

### To Reproduce
1. Go to Settings / Interface
2. Enable numeric Master Lock
3. Try running a plugin (e.g. YouTube)

### Informations
 - LE Version: nightly-20210913-619146d (has been the case in earlier versions pre-10 too; unsure when this started)
 - Hardware Platform: RPi4

### Log file
Should be irrelevant here.

### Additional context
I am using the Master Lock exclusively to restrict access to certain Sources (Settings/Media/Library/Videos).
The correct password is accepted under Power Options / Enter master mode or when trying to access restricted sources.

**Comment by chewitt** [comment]
I'm closing this here because it's an issue with Kodi not LE. Please use the Kodi issue tracker: https://github.com/xbmc/xbmc/issues
