### ISSUE TITLE
[BUG] LE rebooted after copy file action in file manager

### ISSUE THREAD

**Issue by rilyntar** [LibreELEC/LibreELEC.tv#5656]
### Describe the bug
When I copied a tar file from sdcard to hdd using the build in file manager, LE rebooted after copy was done.

### To Reproduce
1. plugin hdd and sdcard each to usb
2. Go to 'settings' -> 'file manager'
2. select source path (in my case a sdcard) on the left panel, and target path (in my case a hdd) on the right
3. with mouse select file on sdcard (source) to copy and right click to open file menu
4. click copy
5. when copy is finished boot logo appeared, then the kodi logo, and then the initial kodi menu appeared

### Informations
 - LE Version: [10]
 - Hardware Platform: [RPi4b 8GB]
 - LE installed on micro sdcard
 - usb hdd plugged in usb hub
 - usd sdcard reader plugged in usb hub
 - mouse and keyboard attached

### Log file
http://ix.io/3zg8 - debug log file
https://pastebin.com/PG7iWMjt - kodi crashlog

### Additional context
The tar file was copied and I was able to load the LE setting from this backup.

**Comment by heitbaum** [comment]
@rilyntar us this still an issue in LE10/11? Please reopen if that is the case.
