### ISSUE TITLE
Raspberry Pi TV HAT not working[BUG]

### ISSUE THREAD

**Issue by jfilaa** [LibreELEC/LibreELEC.tv#5697]
### Describe the bug
Raspberry Pi TV HAT not working. RPi4 TV HAT is not detected.

**Comment by jfilaa** [comment]
update

**Comment by heitbaum** [comment]
Hi @jfilaa please share further details and. Logs if this is still an issue. Use of the forum may give you a greater audience for the issue. Thanks,
