### ISSUE TITLE
[RFE] On ACPI power button events, the system shut shutdown immediately 

### ISSUE THREAD

**Issue by oliv3r** [LibreELEC/LibreELEC.tv#5706]
### Describe the bug
When pressing the shutdown button on a PC (or a gpio on a pi?) the system pop's up a dialog, asking what to do. As the system doesn't have any user input (keyboard, ok button etc) generally speaking, which in turn requires the user to grab a remote and confirm his choice. With the remote in hand, one might as well shutdown from there, making the actual physical powerbutton useless.

This behavior seems to be triggered by using `ActivateWindow(ShutdownMenu)` instead of `XBMC.Quit` on the power button event. Changing this would make the button function as expected, pushing it when the system is turned off; the system turns on; pushing it when the system is turned on; it turns off again. If the user prevents 'suspending' instead of power off; there are of course dedicated ACPI events for that. Power-off, should do just that, power off.

See https://forum.kodi.tv/showthread.php?tid=204450 for some historical information.

### To Reproduce
1. push the button on a PC (ACPI power-off event)
2. See power menu instead of power-off action taking place

### Informations
 - LE Version: 10.0.0
 - Hardware Platform: x86_64 PC (AMD Radeon APU)

**Comment by heitbaum** [comment]
Closing as addressed by pr #8161
