### ISSUE TITLE
[BUG] No more audio with LE 11 on Rock64 (since kernel 5.14?)

### ISSUE THREAD

**Issue by diederikdehaas** [LibreELEC/LibreELEC.tv#5734]
### Describe the bug
When playing a video, I see the video/picture part playing, but there is no sound.
When playing an audio file, I get visual cues that it is playing, but there is no sound.

I had been using nightlies with LE 11 and they worked fine at first (and I'm inclined to think better then LE 10 release). But it appears that since the upgrade of the kernel to 5.14, it stopped working. LE 10 works fine. I usually update by `wget`-ing the DL URL in `/storage/.update/` but it appears it won't save a backup copy and I didn't save/backup one myself, so I can't verify whether LE 11 with 5.13.x kernel indeed (still) works fine.

By studying your amazing work :+1: I have been able to get various multimedia features of the Rock64 working on a Debian kernel. And there I noticed a regression with 5.14.x kernels too. While I had multichannel audio, since 5.14 I only had stereo (fallback). I reported that to Debian here: https://bugs.debian.org/995923
What I found out earlier today is that upstream commit 907f0a3051869a61499905377212500155bd28ec broke it and when I build and booted into a 5.14 kernel with that commit reverted, I got my multichannel audio back :-)
So it could be that's also what broke audio on LE nightlies.

### To Reproduce
1. Go to Movies/TV shows/Music/Videos
2. Play audio or video file
3. Don't hear the audio (part) of the multimedia file. There are no errors reported afaik

### Informations
 - LE Version: 11 (nightly builds)
 - Hardware Platform: Rock64

**Comment by knaerzche** [comment]
This issue gets fixed in https://github.com/LibreELEC/LibreELEC.tv/pull/5749 - please test

**Comment by knaerzche** [comment]
You'll have to enable https://github.com/LibreELEC/LibreELEC.tv/blob/master/projects/Rockchip/devices/RK3328/linux/default/linux.aarch64.conf#L3842 for Analog audio on RK3328.

I'm closing this, as the is issue is solved now.

**Comment by diederikdehaas** [comment]
Thanks so much :-)
I do have that module (as module, not builtin), but it looks like I need other things (too). I'll figure it out :)

**Comment by diederikdehaas** [comment]
I just DL-ed `LibreELEC-RK3328.arm-11.0-nightly-20211011-27d9660-rock64.img.gz` and booted into that. While I didn't hear sound at first as before, after going to System -> Audio and changing the audio output device, everything was working again, including multichannel audio :D
