### ISSUE TITLE
[FEATURE] I have a source code for Tilk 9082XS WIFI Driver

### ISSUE THREAD

**Issue by Marcin666** [LibreELEC/LibreELEC.tv#5801]
Hello,
I dont know how to contact team to support you but AFAIR you had problems with AmLogic devices with Tilk 9082xs wifi driver because lack of source code.
I have it - how can i pass this to Your staff?

**Comment by heitbaum** [comment]
Thanks for info.
Closing issue as this is a Realtek driver addition - the team have reviewed.
