### ISSUE TITLE
Release 10.0.1 has no GIT-TAG?!

### ISSUE THREAD

**Issue by the-dreamer** [LibreELEC/LibreELEC.tv#5843]
As written in Subject. There is no Tag for Release 10.0.1

### To Reproduce
2. Play '....'
3. See error

### Informations
 - LE Version: [e.g. 9.2.1]
 - Hardware Platform: [e.g. RPi3]

**Comment by chewitt** [comment]
Fixed with https://github.com/LibreELEC/LibreELEC.tv/releases/tag/10.0.1
