### ISSUE TITLE
[BUG] Unable to edit any configuration files from SSH 

### ISSUE THREAD

**Issue by Eshanepicfighter** [LibreELEC/LibreELEC.tv#5875]
### Describe the bug
Unable to edit any configuration files via an SSH connection. Even after remounting with read and write permissions, I cannot edit any file in the /etc directory.

### To Reproduce
1. SSH into a Libreelec Device
2. Remount the / directory with read and write permissions
3. CD into the /etc/systemd/ directory
4. Edit the timesyncd.conf file and try saving changes

### Informations
 - LE Version: [e.g. 9.2.1]
 - Hardware Platform: [e.g. RPi3]

### Additional context
Using the latest dev built of Libreelec 11.0

**Comment by antonlacon** [comment]
This isn't a bug; write permissions still won't allow changes to a read-only squashfs image.

You can make your intended changes in `/etc/system.d/timesyncd.conf.d/` in `/storage/.config/timesyncd.conf.d/` instead. If you have additional support questions, please use the forums: https://forum.libreelec.tv/

**Comment by Eshanepicfighter** [comment]
Sorry to continue the issue but I'm having some difficulties using the LibreELEC forum. 

Would I just create a new timesyncd.conf file in that directory to edit the file?

**Comment by lrusak** [comment]
LibreELEC uses a squashfs root file system.

Please use the forum for support. https://forum.libreelec.tv/
