### ISSUE TITLE
Libreelec nightly show boot screen image when changing the resolution other than 1920x1080 on amd rx 6600 xt

### ISSUE THREAD

**Issue by e-ru** [LibreELEC/LibreELEC.tv#5918]
### Describe the bug
The boot screen image shows up every time when changing the resolution other than 1920x1080.
This happens in the `System/Settings/Display/Resolution` Option and during video playback in the video options menu.

### To Reproduce
* Change resolution in System/Settings/Display/Resolution
or
* Change resolution in video options menu during video playback

### Informations
 - LE Version: nightly 20211024-73f3241
 - Hardware Platform: x86-64, cpu: intel 11400, gpu: rx 6600 xt

### Log file
http://ix.io/3G1U

### Additional context
-

**Comment by lrusak** [comment]
Please report the bug to Kodi.

Your device is failing the atomic commit for some reason.

Please try and enable debug logging when posting a log.

Also post the output of the `modetest` command. Use `modetest | pastebinit`

**Comment by e-ru** [comment]
ok thank you

i've mentioned this issue in the xmbc issue as well

regards
erik

**Comment by heitbaum** [comment]
@e-ru  - is this still an issue? Is so can you please update this ticket with the current status and reopen this ticket.
