### ISSUE TITLE
The downloadlink http://releases.libreelec.tv/LibreELEC.USB-SD.Creator.Win32.exe ist http instead of https. Most browsers decline a download.

### ISSUE THREAD

**Issue by galexey** [LibreELEC/LibreELEC.tv#5924]
### To Reproduce
2. Play '....'
3. See error

### Informations
 - LE Version: [e.g. 9.2.1]
 - Hardware Platform: [e.g. RPi3]

**Comment by lrusak** [comment]
Please post in the forum under website feedback.

**Comment by CvH** [comment]
@galexey tx fixed
