### ISSUE TITLE
[RFE] - linux: enable CONFIG_RTL8XXXU

### ISSUE THREAD

**Issue by heitbaum** [LibreELEC/LibreELEC.tv#5950]
now that rtl8xxxu is more stable, can this be added back into mainline? see https://forum.libreelec.tv/thread/10925-use-mainline-rtl8xxxu-driver/

rtl8xxxu driver works well for my various USB WiFI adapters with buster/bullseye RPiOS.

_Originally posted by @reukiodo in https://github.com/LibreELEC/LibreELEC.tv/issues/287#issuecomment-984344175_

**Comment by heitbaum** [comment]
@CGarces - is this an option? Viable?

**Comment by chewitt** [comment]
It needs to be combined with `CONFIG_RTL8XXXU_UNTESTED=y` as the number of devices which are formally reported as working is rather small .. but it's probably the right direction and thing to do.

**Comment by CGarces** [comment]
> @CGarces - is this an option? Viable?

Is something that we must do sooner of later.
RTL8XXXU should replace RTL8192EU and RTL8192CU

**Comment by heitbaum** [comment]
Suggest we PR this change post 5.17 is merged into master then?
