### ISSUE TITLE
[Request] Pi0W2 support in LE9

### ISSUE THREAD

**Issue by tergo** [LibreELEC/LibreELEC.tv#5971]
Pi0W2 released in late October. It is basically a cut-down Pi3 with less RAM. 

Perhaps there can be a LE 9.2.9 image to provide Pi0W2 support with a stable Kodi ? Some forum members already got it working. 

Otherwise a stable release supporting this hardware is very far away since LE10 seems to have skipped support for Pi3 entirely and LE11 will not be stable for at least 1 year (?). 

It can be released without auto-update.

**Comment by chewitt** [comment]
The legacy codebase would be a fit for RPi0W2, so there is logic to the request, but retrofitting support will enourage users to purchase boards for LE use, and that will lead to support and expectation problems in the future. There are no plans for an LE 9.2.9 release and no current plans to promote RPi02W for LE use as despite the boost to CPU spec, 512MB RAM is borderline for a good LE10/LE11 experience; which is also why we announced the end of support for RPi0 and RPi0W before LE10 releases started (we regard RPi2/3 releases as delayed, not postponed to LE11). If people want to experiement with an RPi02W board there are nightly images that should work. As there are no plans here, I'll close the ticket.
