### ISSUE TITLE
[BUG] Chrome browser doesn't start in presence of specific, custom audio device config

### ISSUE THREAD

**Issue by pohutukawa** [LibreELEC/LibreELEC.tv#5982]
### Describe the bug
After upgrading to the current version of the Chrome browser add-on, Chrome does not launch any more.

### To Reproduce
1. Configure a custom audio device (in my case `plughw:0,3`, which used to work for years)
2. Start Chrome via the add-on in the Kodi UI
3. See a `TypeError` in the Kodi logs

### Informations
 - LE Version: 10.0.1
 - Hardware Platform: 64-bit, generic x86

### Log file
```
2021-12-15 17:19:37.756 T:972     ERROR <general>: ## Chrome Error:TypeError('expected str, bytes or os
.PathLike object, not NoneType')
```

### Additional context
I have debugged the problem. In the process, I have enhanced the logging output to be more specific and meaningful.

The parts of the launch environment produced for the Chrome launch were as follows:

```
{
    'VAAPI_MODE': 'intel',
    'WINDOW_MODE': 'maximized',
    'RASTER_MODE': 'off',
    'DARK_MODE': 'false',
    'AUDIO_DEVICE_TYPE': None
}
```
The `'AUDIO_DEVICE_TYPE': None` caused the `TypeError`, additionally the `ALSA_DEVICE` environment variable was missing in the latest version, providing the specific custom audio device to allow Chrome to provide audio.

I have fixed the underlying problem and created a PR. I have also changed the launch of the `subprocess` to be more pythonic by avoiding the `shell=True` parameter, and cautiously cleaned up minor issues around the places affected by the bug (without 

Let's get this into the next mainstream version released. The PR is #5981

Hope that helps.

**Comment by heitbaum** [comment]
Closed in works incorporated into
- #7101
- #7310
