### ISSUE TITLE
[BUG] Build error after PR #5944 was merged

### ISSUE THREAD

**Issue by pretoriano80** [LibreELEC/LibreELEC.tv#6002]
### Describe the bug
ncurses building fails 

### Informations
 - LE Version: LE11
 - Hardware Platform: RPi4

### Log file
[32.log](https://github.com/LibreELEC/LibreELEC.tv/files/7746738/32.log)

**Comment by mglae** [comment]
```
[1;31mCLEAN[0m      ncurses
    [1;31m*[0m      [0;31mRemoving /home/pretoriano/LibreELEC.tv/build.LibreELEC-RPi4.arm-11.0-devel/build/ncurses-6.1-20181215 ...[0m
    [1;31m*[0m      [0;31mRemoving /home/pretoriano/LibreELEC.tv/build.LibreELEC-RPi4.arm-11.0-devel/install_pkg/ncurses-6.1-20181215 ...[0m
```

Clean build is required. Incremental builds do not succeed.

**Comment by pretoriano80** [comment]
Ok, thanks! Will try a clean build and report back

**Comment by pretoriano80** [comment]
After a "distclean"  the error is gone, thanks!

**Comment by shantigilbert** [comment]
FYI: I added `--without-tests` to `PKG_CONFIGURE_OPTS_HOST` and it compiled even without a `distclean`. 
But not sure if the tests are required for ncurses:host

**Comment by mglae** [comment]
You did still update ncurses 6.1 without widechar to 6.3 with widechar?

**Comment by shantigilbert** [comment]
@mglae I just pulled the latest changes, got the same error as the one posted here, added no-test and it compiled.
