### ISSUE TITLE
[BUG] Downloading LibreElec image for RaspberryPi4 from the website

### ISSUE THREAD

**Issue by anujdatar** [LibreELEC/LibreELEC.tv#6007]
### To Reproduce
1. Go to 'https://libreelec.tv/downloads/raspberry/'
2. Click on image download link
3. Nothing happens on chrome unless you do 'right-click -> save link as', on firefox it happens right away. Error says `File not downloaded: Potential security risk.. File uses insecure connection`

### Informations
 - LE Version: 10.0
 - Hardware Platform: Windows

**Comment by RobLoach** [comment]
Looks like the cert for http://releases.libreelec.tv/ expired.

**Comment by heitbaum** [comment]
Known issue with chrome and other modern browsers. Issue is that with mirrors - require to use http, without change to the download mirrors.

**Comment by CvH** [comment]
should be fixed next week, the new mirroring is ready to get deployed if time permits
