### ISSUE TITLE
[BUG] docker logs going to journalctl

### ISSUE THREAD

**Issue by heitbaum** [LibreELEC/LibreELEC.tv#6029]
Review docker configuration - as console also outputting to journalctl.

https://docs.docker.com/config/containers/logging/

I believe this might be that change of behaviour that we are seeing: 

https://github.com/systemd/systemd-stable/blob/a420d71793bcbc1539a63be60f83cdc14373ea4a/NEWS#L791-L792

        * systemd-journald's own logging messages are now also logged to the
          journal itself when systemd-journald logs to /dev/kmsg.

**Comment by lrusak** [comment]
Why do you think this is a bug?

https://github.com/LibreELEC/LibreELEC.tv/blob/140ad28a258167e0e87daf1e474db37215b2caf3/packages/addons/service/docker/source/system.d/service.system.docker.service#L12

**Comment by heitbaum** [comment]
Hi @lrusak - then its strange - it wasn’t doing that before. `docker ubuntu bash; make image` All that output is going to both journald and my ssh session.

**Comment by lrusak** [comment]
> Hi @lrusak - then its strange - it wasn’t doing that before. `docker ubuntu bash; make image` All that output is going to both journald and my ssh session.

Oh wait, do you mean the LibreELEC build container?

**Comment by heitbaum** [comment]
![image](https://user-images.githubusercontent.com/6086324/147545943-ea5a21af-e118-4590-b5d3-b15f7fe99039.png)

Here is the image - yup - even weirder - now that I am at home and can see it on the big screen at my desk. need to dig in to this further ... maybe `systemd 250`

**Comment by heitbaum** [comment]
Confirmed this is a change (regression between systemd 249.7 and 250)

**Comment by heitbaum** [comment]
First part of the reading seems to indicate for “interactive shell” based containers:
`--log-driver none` should be the setting. 
- Test and update the https://github.com/LibreELEC/LibreELEC.tv/blob/master/tools/docker/README.md 
- more reading at https://docs.docker.com/config/containers/logging/configure/
