### ISSUE TITLE
[Feature request] kernel options to allow Kubernetes K3s

### ISSUE THREAD

**Issue by mossroy** [LibreELEC/LibreELEC.tv#6098]
As Docker is already available on LibreELEC (through the add-on), I investigated if it was possible to run [k3s](https://k3s.io/) (lightweight Kubernetes distribution).
My intention is to make my LibreELEC machine part of a self-hosted k3s cluster. It would take advantage of the power and capabilities of the machine to run some self-hosted services.

I managed to make it run (currently with some dirty hacks). See https://github.com/k3s-io/k3s/issues/4859

But I had to recompile LibreELEC, after adding several kernel options, on branch libreelec-10.0.

Here are the needed kernel options :

-  CONFIG_CGROUP_PIDS
-  CONFIG_USER_NS
-  CONFIG_NETFILTER_XT_MARK
-  CONFIG_NETFILTER_XT_CONNMARK
-  CONFIG_NETFILTER_XT_TARGET_CONNMARK
-  CONFIG_NETFILTER_XT_TARGET_MARK
-  CONFIG_NETFILTER_XT_TARGET_NFLOG
-  CONFIG_NETFILTER_XT_MATCH_COMMENT
-  CONFIG_NETFILTER_XT_MATCH_LIMIT
-  CONFIG_NETFILTER_XT_MATCH_MARK
-  CONFIG_NETFILTER_XT_MATCH_MULTIPORT
-  CONFIG_NETFILTER_XT_MATCH_PHYSDEV
-  CONFIG_NETFILTER_XT_MATCH_STATISTIC
-  CONFIG_IP_SET
-  CONFIG_IP_VS
-  CONFIG_IP_VS_RR
-  CONFIG_IP_VS_WRR
-  CONFIG_IP_VS_SH
-  CONFIG_BRIDGE_VLAN_FILTERING
-  CONFIG_VXLAN

I also had to workaround the fact that the root filesystem is a read-only squashfs, but I understand it's certainly by design to allow easier upgrades of LE.

NB : I did that on an amd64 machine, but it would probably work on most other architectures too : k3s also supports armhf and arm64

**Comment by chewitt** [comment]
Closing as per comment here https://github.com/LibreELEC/LibreELEC.tv/pull/6100#issuecomment-1008312393
