### ISSUE TITLE
[TRIVIAL] Typo in comment ?

### ISSUE THREAD

**Issue by vincele** [LibreELEC/LibreELEC.tv#6107]
https://github.com/LibreELEC/LibreELEC.tv/blob/9b9ecf8724d489c91a9f6deaed51c592a9ee1cea/projects/Allwinner/patches/linux/0036-wip-h3-h5-cvbs.patch#L283

Isn't this "conversion" instead of "conversation" ?

**Comment by jernejsk** [comment]
sure, it's a typo, but it doesn't change anything functionality wise. If you want, you can open PR with a fix.

**Comment by heitbaum** [comment]
@vincele - closing the bug report - but would be happy to accept a PR for the update to the sources.
