### ISSUE TITLE
[BUG] Logitech K400 keyboard types by itself (looks like a driver issue?)

### ISSUE THREAD

**Issue by motosba** [LibreELEC/LibreELEC.tv#6109]
### Describe the bug
Logitech K400 keyboard types by itself

### To Reproduce
1. Plug in a wireless Logitech K400+ keyboard combo
2. Start playback
3. Pause playback with space
4. Playback will resume by itself after a while

### Informations
 - LE Version: 10.0.1
 - Hardware Platform: RPI4b

### Log file
N/A

### Additional context
Looks like a driver not issue. This only happens with this keyboard. I don't have issues with the keyboard while using it for other purposes.

**Comment by eldersixpack13** [comment]
how long is "a while" ?

tried to reproduce it on nightly and an Intel nuc8 with an 2 month old k400 plus: movies keeps stopped

**Comment by heitbaum** [comment]
@motosba - please reopen if this is still an issue - and provide an update.
