### ISSUE TITLE
[BUG] Kodi crashed when playing a video file

### ISSUE THREAD

**Issue by ThomasTraineau** [LibreELEC/LibreELEC.tv#6182]
### Describe the bug
When playing a video file, libreelec crashes (black screen and then no sound)

### To Reproduce
Play a movie and see what happens

### Informations
 - LE Version: 10.0.1
 - Hardware Platform: RPi4B

### Log file
http://ix.io/3OgC

### Additional context
The video is played from an external hard drive. I don't have any specific config, I just flashed libreelec on an sd card, started the rbpi and tried to open a video file

**Comment by heitbaum** [comment]
Please use the forums for support - https://forum.libreelec.tv/ 
I have had a look at the Log file already - and there is not a kodi.log.
