### ISSUE TITLE
[BUG] Mysql addon configuration

### ISSUE THREAD

**Issue by denics** [LibreELEC/LibreELEC.tv#6185]
### Describe the bug
When a user does not specify a real IP or hostname in the **<\*base>\<host>** configuration in advancedsettings.xml and instead he uses *localhost* or *127.0.0.1*, LE try to connect to **/tmp/mysqld.sock** that does not exists.

### To Reproduce
1. install mariadb addon
2. `vi .kodi/userdata/advancedsettings.xml`
    ```xml
    <advancedsettings>
    ...
    <videodatabase>
      <type>mysql</type>
      <host>localhost</host>
      <port>3306</port>
      <user>kodi</user>
      <pass>kodi</pass>
    </videodatabase>
    ...
    </advancedsettings>
    ```
3. See error
    ```
    2022-02-03 11:58:04.558 T:1429    ERROR <general>: Unable to create new database
    2022-02-03 11:58:04.558 T:1429    ERROR <general>: Unable to open database: MyVideosXXX [2002](Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2))
    ```

### Informations
 - LE Version: 10.0.1 (RPi4.arm)
 - Hardware Platform: Linux kodi 5.10.76 SMP Sat Oct 30 00:03:05 CEST 2021 aarch64 GNU/Linux

### Additional context
Two solutions are possible:

- document in the wiki how to create the advancedsettings.xml including a real IP or hostname
- fix the socks location issue

PS: I love Libreelec I have a portable one on a RPI3 and my home theater on a RPI4. Thanks

**Comment by lrusak** [comment]
Might want to make a forum thread on the Kodi forum about your issue. We simply consume their application.
