### ISSUE TITLE
[BUG] ActiveAE - large audio sync error

### ISSUE THREAD

**Issue by eldersixpack13** [LibreELEC/LibreELEC.tv#6187]
### Describe the bug

was watching SAT-TV for some minutes (< 5) after a reboot.
suddenly the audio got out of sync: mimik and speach doesn't match, stuttering audio
stopping the tv channel and starting it: all was fine again

channels were selected via EPG

**this bug is *not* reliable reproduceable for me, it comes from time to time. 
noticed it first time: ~15 nightly ago (daily update here)** 

### To Reproduce
1. watch TV
2. wait
3. 

### Informations
 - LE Version:  **nightly**-20220202-5347c5e
 - Hardware Platform:  x86_64, Intel NUC 8i3BEH

### Log file

complete kodi.log, systemd journal and tvh's service.log is here for download:
https://app.mediafire.com/1bkbptqe9lylw

noticed audio out of sync at ~21:50

**Comment by eldersixpack13** [comment]
@heitbaum 
is it fine by you that I open another bug report ? 
(I'm no native english speaker, so I sometimes get think wrong...)

**Comment by heitbaum** [comment]
> @heitbaum
> is it fine by you that I open another bug report ?
> (I'm no native english speaker, so I sometimes get think wrong...)

No problems.

**Comment by eldersixpack13** [comment]
- no code reader here -
that said, but could it be that a fix for this bug is in the pipe:
https://github.com/xbmc/xbmc/pull/20938

**Comment by a1rwulf** [comment]
@eldersixpack13 do you have refreshrate switching enabled?

**Comment by eldersixpack13** [comment]
huhhh, don't know (exactly)
settings regarding refresh rate are:

**Player**
- Video => "Adjust display refresh rates" is OFF

**System**
- Display
   => "Allow 3:2 pulldown refresh rates" is ON
   => "Allow double refresh rates" is ON 

was my answer a (at least partly) useful answer ?

**Comment by eldersixpack13** [comment]
today I had the audio sync error while watching a movie from german mediathek.
alas debug was off.
http://ix.io/3OGB

=> time: 2022-02-04 23:52:05.322 T:626

**Comment by a1rwulf** [comment]
As you don't have refreshrate switch enabled, I don't think https://github.com/xbmc/xbmc/pull/20938 will fix your issue.
Your log looks a bit like too less data is incoming to keep everything going, but I'm not sure.

**Comment by eldersixpack13** [comment]
well, all is via LAN
and more important:
- mostly audio sync error occur when I first time start a movie out of the mediathek or from Sat-TV (within the first ~10 minutes)
- when this error occured and I stop and restart the movie again all is fine (for a long or all the time)

weird !

**Comment by heitbaum** [comment]
@eldersixpack13  - the upstream patch in in the nightly kernels now. Are you still experiencing these issues?

**Comment by eldersixpack13** [comment]
@heitbaum, 
no since a  long time already (one/two nightlies following 5347c5e).

btw:
~2 days ago I thought to close this, too
telepathy ?
;-)

**Comment by eldersixpack13** [comment]
this bug seems to be fixed.
