### ISSUE TITLE
[BUG] jernejsk / LibreELEC.tv does not start at A20 Hardware

### ISSUE THREAD

**Issue by gitflo2000** [LibreELEC/LibreELEC.tv#6200]
### Describe the bug

A20 Hardware does not start with libreelec A20 images

### To Reproduce
1. Go to http://jernej.libreelec.tv/images/a20/
2. use rufus 3.17 to write image on SD Card
3. insert SD Card to Box
4. Box does not start

### Informations
 - LE Version: LibreELEC-A20.arm-9.80
 - Hardware Platform: Box_20130531
 - pre Installed Android Version: 4.2.2, A10-20, 3.3.0 ck@ck-desktop#2, Fri May 31 17:18:21 CST2013, RSH-A10-D-20130531
 - 
### Log file

starting USB...
no working controllers found
no ethernet found
no ethernet@IC50000
### Additional context

The Hardware is this:
Inakustik Internet TV Box Android Mini-PC (A7) 2 x 1.0 GHz 1 GB Android™ 4.2
Bestell-Nr.:
779273 - 62
Hst.-Teile-Nr.:
00415200
EAN:
4001985510139
https://www.conrad.de/de/p/inakustik-internet-tv-box-android-mini-pc-a7-2-x-1-0-ghz-1-gb-android-4-2-779273.html 

it has Allwinder A20 Chipset

**Comment by jernejsk** [comment]
Closing as it's not even in official LE repository and totally unsupported.
