### ISSUE TITLE
[BUG] Bluetooth pairing with HifiBerryOS Raspberry Pi 4 not possible

### ISSUE THREAD

**Issue by Velofil** [LibreELEC/LibreELEC.tv#6207]
### Describe the bug
I am trying to pair my LibreELEC 10.01 with my HifiBerryOS Raspberry Pi4 to stream the audio signal to my stereo reciever. Pairing other clients works without problem. LibreELEC refuses to pair and gives "Authentication Error". 

### To Reproduce
2. Play '....'
3. See error

### Informations
 - LE Version: 10.01
 - Hardware Platform: RPi4 4GB

### Log file
will do :-)

**Comment by heitbaum** [comment]
@Velofil - Please share the logs / use the forum for support.

**Comment by heitbaum** [comment]
Stale issue - closing. Please reopen if further information is available.
