### ISSUE TITLE
[request]RPi 4 Model B Rev 1.5 not supported with 9.2

### ISSUE THREAD

**Issue by stefanides** [LibreELEC/LibreELEC.tv#6238]
### Describe the bug
I have purchased one more Pi4, which now comes with hw revision 1.5. The 9.2 release cannot be booted on it. 

### To Reproduce
1. Download 9.2 image from https://libreelec.tv/downloads/raspberry/, flash to SD
2. Boot inside hw revision 1.5
3. Error "this board requires newer software" is visible on attached HDMI

or
1. Take SD card with working 9.2 installation from Pi4 hw revision 1.1
2. Boot inside hw revision 1.5
3. The same error "this board requires newer software" is visible on attached HDMI

### Informations
 - LE Version: 9.2.8
 - Hardware Platform: 
```
# cat /proc/cpuinfo
processor	: 3
BogoMIPS	: 108.50
Features	: fp asimd evtstrm crc32 cpuid
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 3

Hardware	: BCM2835
Revision	: a03115
Serial		: 10000000........
Model		: Raspberry Pi 4 Model B Rev 1.5
```
### Log file
See the same/similar (versions might differ) screenshot e.g. here https://github.com/libretro/Lakka-LibreELEC/issues/962

### Expected behaviour
The image should either be working on all Pi4 revisions (I have tested to copy start.elf and fixup.dat from Libreelec 10 - the OS starts on hw 1.5, however without HDMI)
Or the download page https://libreelec.tv/downloads/raspberry/ should at least mention "RPi4 is not supported with HW revision 1.5" for 9.2 release

**Comment by heitbaum** [comment]
Hi @stefanides 

both the 1.4 and 1.5 are release after 9.2. They both have been worked on with LE10 and LE11. No further releases of LE9.2 are planned. 

The following detail, the new hardware that has been shipped.
- https://pip.raspberrypi.com/documents/RP-001247-PC/RP-001247-PC-1.pdf
- https://pip.raspberrypi.com/documents/RP-001248-PC/RP-001248-PC-2.pdf

If you would like to suggest an update to the website - happy to review a PR for - https://github.com/LibreELEC/website
