### ISSUE TITLE
Question on Raspberry Pi VNC

### ISSUE THREAD

**Issue by 32Dexter** [LibreELEC/LibreELEC.tv#6322]
Hi, i use LE 10.0.2 on my RPi 3B+, it works well for me, but a have a question:
Why service.system.dispmanx_vnc now this addon have been removed?
How i can connect to kody remote desktop with VNC?
Thanks

**Comment by lrusak** [comment]
It's not possible anymore.

Please use the forum for further support. https://forum.libreelec.tv/
