### ISSUE TITLE
[BUG] service.ttyd (Web SSH Terminal) keeps restarting

### ISSUE THREAD

**Issue by nicozanf** [LibreELEC/LibreELEC.tv#6354]
### Describe the bug
Every around 90 seconds, the ttyd service plugin is restarted. If you change the onSettingsChanged  function to a simple 'pass' the problem is solved - it seems that it fails to properly identify changes to the settings, and hence it always keeps reloading the daemon.

### To Reproduce
1. install the LE add-on service "Web SSH Terminal" =ttyd
2. login on the web page or just monitor the ttyd process for a couple of minutes

### Informations
 - LE Version: 9.2.8
 - Hardware Platform: RPi3
- standard "Web SSH Terminal" 9.2.0.100

**Comment by heitbaum** [comment]
Hi @nicozanf can you please test and confirm that this is working/not working on LE10/LE11 and we can look at it. no further updates are being done on the LE9 codebase. For support discussions - please use the forum. https://forum.libreelec.tv/
