### ISSUE TITLE
[BUG] "adjust display refresh rate = on" leads to black screen after 2 second play

### ISSUE THREAD

**Issue by Isayso** [LibreELEC/LibreELEC.tv#6355]
### Describe the bug
If you have the Adjust display refresh rate option on, you get a very annoying behavior on short video clips. The video starts, after 2 s it stops with black screen for 1 s, than runs to the end. Its is not an option to switch it off if you have videos with 30 and 60Hz refresh one after the other.

### To Reproduce
1. Go to 'Adjust display refresh rate', choose any option except 'off'
2. Put two or more short videos in playlist queue and play
3. Video starts, plays 2 s, stops 1s, plays to the end. On next queued video the same

### Informations
 - LE Version: 10.0.2
 - Hardware Platform: RPi3+

### Additional context

This is for playlist of short video clips with different refresh rates very annoying. Would be good if the refresh rate ist adjusted before the video starts, a blank screen between clips is not a problem for me.

**Comment by heitbaum** [comment]
Please confirm if still an issue in LE11/LE12

**Comment by Isayso** [comment]
Tested on latest LE12 Nightly: 
There is sometimes a short blank and audio stop on, much better than before, it is acceptable. 
But, because 60Hz videos do not run anymore, the option off is the preferred anyway. 
BTW: The "Play from here " option in context menu in playlist .m3u files does not work, plays only one.

**Comment by heitbaum** [comment]
@Isayso - for the m3u issue - please raise it on the LE forum. If it works in le11 and doesn’t in le12 - then it would be good to log an issue with Kodi to be fixed during development.
