### ISSUE TITLE
[BUG] Bookmark Thumbnails Not Generating (RPi4)

### ISSUE THREAD

**Issue by mediamoshpit** [LibreELEC/LibreELEC.tv#6389]
### Describe the bug
When bookmarks are added, thumbnails are being generated as a black box or random graphic pixel noise rather than the expected still shot of what is currently on screen.

### To Reproduce
1. Play any video.
2. Open Bookmark menu and save a bookmark.
3. Observe result.

### Informations
 - LE Version: 10.0.2 (Behavior observed as far back as 10.0.0 with my introduction to LE)
 - Hardware Platform: RPi4b 4GB

### Log file
https://paste.kodi.tv/otorusamur

**Comment by heitbaum** [comment]
Closing as le10 no longer is supported. If still an issue in LE11 - please raise a forum post
