### ISSUE TITLE
[BUG] Bluetooth keyboard connectivity issue | Logitech K850

### ISSUE THREAD

**Issue by anshulosahub** [LibreELEC/LibreELEC.tv#6475]
**Platform**: Raspberry pi3, ARMV7 with LibreELEC Build(19.4.0), Git (19.4-Matrix), Compiled: 2022-03-05
**Summary**: Was able to connect the wireless mouse (M720) , which comes with Logitech K850 keyboard but the keyboard setup was not completed due to a bug.
**Expected behaviour**: How keyboard connects generally: there is a pop-up window displaying a 6-digit code (on Android/ iOS/ Windows), on the keyboard you have to enter that, to connect. 
**Bug**: On LibreELEC I am getting the pop-up but that's blank, no number/ pin to enter, and hence unable to connect
![bug](https://user-images.githubusercontent.com/64097836/167498276-17c96669-ce6e-4e05-868b-6e3ab3352eae.png)

**Comment by antonlacon** [comment]
Should be resolved on 10.0.3. Please re-test.

**Comment by chewitt** [comment]
Closing as the issue was resolved in 10.0.3 (and master). If not, please request reopen of file a new bug report. Thanks!
