### ISSUE TITLE
LE11 RPi4 - No HDMI audio post 20220528-7faa80c 

### ISSUE THREAD

**Issue by camelreef** [LibreELEC/LibreELEC.tv#6575]
Hello,

As per this forum topic: https://forum.libreelec.tv/thread/25744-no-hdmi-audio-after-upgrade-to-le-11-nightly-20220530

Here is my data and debug logs:

**4GB RPi4, dual headed (hdmi0 to 4K TV, hdmi1 to HDMI 1.4 Receiver)**
No HDMI audio of any kind after 20220528-7faa80c (tested until nightly-20220607-9d4c846) - Reverting to 20220528-7faa80c gives me the audio back.
- Dual-headed lounge Pi4 - NO AUDIO - 20220601-0e57a30 debug log: http://ix.io/3ZbJ
- Dual-headed lounge Pi4 - GOOD AUDIO - 20220528-7faa80c debug log: http://ix.io/3ZbO

**I have the same Pi model and revision (Raspberry Pi 4 Model B Rev 1.1) solely connected to a TV that doesn't exhibit the issue at all** when using a post 20220528-7faa80c image.
- Single headed bedroom Pi4 - GOOD AUDIO - 20220601-0e57a30 debug log: http://ix.io/3ZbP
- Single headed bedroom Pi4 - GOOD AUDIO - 20220528-7faa80c debug log: http://ix.io/3ZbU

Both Pis were on the January Bootloader EEPROM when generating those debug logs. Updating to the April Bootloader EEPROM didn't change a thing.

I'm hoping that these will help see something. Ask for more data if needed!

**Comment by pretoriano80** [comment]
The working RPi4 is connected to the TV thru HDMI0?
What happens on the dual headed one if you connect it only to the TV (trying both with HDMI0 and HDMI1) ?

**Comment by HiassofT** [comment]
Can you test with the build from here https://forum.libreelec.tv/thread/24783-tv-avr-turns-back-on-right-after-turning-them-off/?postID=170126#post170126 with the cmdline.txt option mentioned?

If that helps then testing with `vc4.force_hotplug=2` would also be interesting.

There are quite a lot of HDMI-A-2 messages in your log which indicate it might be related to the hotplug signal of your AVR on the second HDMI port (AVR weirdness or cable issues might also cause this, OFC).

**Comment by camelreef** [comment]
> The working RPi4 is connected to the TV thru HDMI0?

Yes.

> What happens on the dual headed one if you connect it only to the TV (trying both with HDMI0 and HDMI1) ?
I can try that tomorrow and report.

Something to be noted: I have saved EDID files loaded at boot on the dual headed Pi.

**Comment by camelreef** [comment]
> Can you test with the build from here https://forum.libreelec.tv/thread/24783-tv-avr-turns-back-on-right-after-turning-them-off/?postID=170126#post170126 with the cmdline.txt option mentioned?
> 
> If that helps then testing with `vc4.force_hotplug=2` would also be interesting.

I will test that tomorrow (I'm in the UK) and report.

> There are quite a lot of HDMI-A-2 messages in your log which indicate it might be related to the hotplug signal of your AVR on the second HDMI port (AVR weirdness or cable issues might also cause this, OFC).

I am loading EDID files at boot. My Denon AVR was all confused by the 4K HDR TV's EDID and was returning total nonsense, so I had to use an EDID file saved when the AVR was connected to my old 1080p TV.
This has been working for me for months.
I'm wishing everyday for a new AVR with HDMI 2.x and eARC that would make is all so much simpler and easier, but that upgrade won't be realistic for a while on my end.

**Comment by camelreef** [comment]
> Can you test with the build from here https://forum.libreelec.tv/thread/24783-tv-avr-turns-back-on-right-after-turning-them-off/?postID=170126#post170126 with the cmdline.txt option mentioned?
> 
> If that helps then testing with `vc4.force_hotplug=2` would also be interesting.

I finally got to things, after a 24h delay, life got in the way!

Same negative result with this built, forcing both or only one HDMI port has no effect.

**Comment by camelreef** [comment]
> The working RPi4 is connected to the TV thru HDMI0? 

Yes

> What happens on the dual headed one if you connect it only to the TV (trying both with HDMI0 and HDMI1) ?

I've removed the forced EDID files config from config.txt and cmdline.txt.

No HDMI to AVR. Single headed.

TV only on hdmi0: I have audio. 
TV only on hdmi1: I have audio (but no CEC, which, I believe, is expected)

**Comment by ghtester** [comment]
In my configuration I have no audio on TV only at HDMI0 port. Using FHD resolution.
Perhaps an issue with detected cap[ability of connected HDMI device?
I am going to try connecting another TV / monitor.
All other audio outputs working OK, just the HDMI audio is muted.

**Comment by camelreef** [comment]
Holy cow! 

I used to need fixed EDID files to make dual heading for separate audio and video work. I even had to load an EDID file for the AVR that was saved while connected to a hdmi 1.4 1080p TV, as confusion ensued otherwise.

I have removed that forced EDID config while doing the above test, then rebooted with dual headed connectivity and no forced EDID files.

And all is working perfectly!

Some things, at some point changed, making the recent versions not like my forced EDID setup, and making the system not get confused when accepting EDID from the equipment live.

I will have to force the current EDID files, though, as the AVR doesn't give any EDID is on stand-by. That's not leading to a higher WAF if things go weird and require me to perform a remote reboot.

**Comment by ghtester** [comment]
What LE 11 Nightly build are you running (= which is working) now? The latest available LibreELEC-RPi4.arm-11.0-nightly-20220609-c66e09a.img.gz or even earlier?

**Comment by camelreef** [comment]
> What LE 11 Nightly build are you running (= which is working) now? The latest available LibreELEC-RPi4.arm-11.0-nightly-20220609-c66e09a.img.gz or even earlier?

nightly-20220609-c66e09a (RPi4.arm)

**Comment by ghtester** [comment]
Thanks, it did not work for me (with my old Telefunken TV) even with nightly-20220609-c66e09a. 
Then I tried to uncomment **hdmi_force_hotplug=1** in config.txt & rebooted, the issue persisted. So I connected another TV (LG) to HDMI0 instead of Telefunken and the audio was working on it. 
Then I created the **edid-HDMI-A-1.bin** file using **getedid create** command, disconnected LG, connected Telefunken and the audio was working! 
After that I found about 1 year old and forgotten **edid-HDMI-A-2.bin**  file in /storage/.config/firmware/edid/ folder together with fresh  **edid-HDMI-A-1.bin** . Tried to move both files to another folder & rebooted. The audio was still working with Telefunken TV. Then I tried to copy  **edid-HDMI-A-2.bin**  back to edid folder to check if it was the root of the issue. 
After reboot there was no audio. So I deleted the **edid-HDMI-A-2.bin** and supposed audio should work after reboot but it did not... :-/  Then I put **edid-HDMI-A-1.bin**  back to edid folder, rebooted and audio works...  It's a bit strange but for now I'll keep this edid file forced which looks to be a most reliable 'solution' for me.

**Comment by tibersam** [comment]
Hello all, I am not sure why i can't post this in the forum (at least don't find any post/reply buttons even if logged in), so i post it here
I upgraded recently from 10.0.0 to 10.0.2 on my RPi4. After the update, Audio stopped working. The AV Reciever is connected to hdmi0 (the one closer to the powre cable) and is a Pioneer VSX-529.
I generated the following Logs with pastekodi. For each version i freshly installed libreelec on the sd card and then played the same two videofiles from an USB stick. The only difference between each log is the installed version.

10.0.2 (Audio not working): http://ix.io/3ZZ9
10.0.1 (Audio not working): http://ix.io/3ZZh
10.0.0 (Audio working): http://ix.io/3ZZl

It might be related to this problem and be a regression issue on some Hardware combinations.

**Comment by camelreef** [comment]
BTW, this is fixed from my POV. All is working normally, even better than before, as I do not need weird EDID files hoops anymore.
As I'm not the only one commenting, I will not close this issue yet. @ghtester ?

@tibersam , your issue is with a pretty different release, I don't believe that it's relevant here. I would open another issue if I were you.
