### ISSUE TITLE
[BUG] bash: syntax error: unexpected redirection

### ISSUE THREAD

**Issue by mfizz1** [LibreELEC/LibreELEC.tv#6592]
### Describe the bug

Unexpected behaviour of bash

### To Reproduce
1. Type `bash` in terminal and hit return
2. Type `read first second <<< "hello world"`

Results in:

`bash: syntax error: unexpected redirection`

### Informations
 - LE Version: nightly-20220610-f89b380 (AMLGX.arm)
 - Hardware Platform: Wetek Play 2

Debug log:

http://ix.io/3ZY4

**Comment by HiassofT** [comment]
LibreELEC doesn't ship bash. /usr/bin/bash is busybox's ash with some bash compatible extensions. This doesn't support all bash features though.

In general it's best to stick to POSIX shell when writing scripts.
