### ISSUE TITLE
[BUG] Dvd playback over nfs failed

### ISSUE THREAD

**Issue by A1RF0RCE1** [LibreELEC/LibreELEC.tv#6692]
### Describe the bug

Playback of DVD video folder over nfs fails. 
Error: One or more items failed to play. Check the log for more information.

### To Reproduce
2. Play '....'
3. See error

### Informations
 - LE Version: 11
 - Hardware Plaform: RPi4

### Log file

https://pastebin.com/04qgXYkK

### Additional context

Extra info: https://github.com/xbmc/xbmc/issues/21670

**Comment by enen92** [comment]
While this is purely a libreelec issue since it seems the library is not being properly wrapped I am trying to finally get rid of this on libdvdread upstream: https://code.videolan.org/videolan/libdvdread/-/merge_requests/40

This will solve this and similar issues, let's see if in time for v20 final.

**Comment by lomion0815** [comment]
Is there any workaround known (like using SMB or such)?

**Comment by lomion0815** [comment]
This problem still or again occurs in the latest nightly builds which use the latest xmbc library (libdvd*) versions.

**Comment by lomion0815** [comment]
> While this is purely a libreelec issue since it seems the library is not being properly wrapped I am trying to finally get rid of this on libdvdread upstream: https://code.videolan.org/videolan/libdvdread/-/merge_requests/40
> 
> This will solve this and similar issues, let's see if in time for v20 final.

Its not in time for v20! What next?

**Comment by vpeter4** [comment]
From what I see playing DVD folder works on LE Generic but not on arm build? Is this again some arm issue like Kodi sorting?

**Comment by lomion0815** [comment]
No problems while testing on RPi3 and RPi4 for 2 weeks now. Very grateful for this fix!

**Comment by heitbaum** [comment]
Closing as fixed
