### ISSUE TITLE
[BUG] RPi4: Resuming playback fails with x264 videos encoded with the --open-gop option when DRM Prime hardware acceleration is enabled.

### ISSUE THREAD

**Issue by Groschi** [LibreELEC/LibreELEC.tv#6864]
### Describe the bug
On a RPi 4, resuming playback of some x264-encoded videos fails when the option `Allow hardware acceleration with DRM PRIME` is enabled - instead of launching into fullscreen video playback i get an opaque busy spinner overlay (the spinner itself is not moving). The audio is playing though. It appears to fail on all files encoded with the `--open-gop` option. Files encoded without `--open-gop` seem to work fine. I see this happening with both LE 10.x and current LE 11 nightly builds.

### To Reproduce
1. Go into the player settings, enable both `Allow using DRM PRIME decoder` and `Allow hardware acceleration with DRM PRIME`
2. Download the footage i've encoded with and without `--open-gop`:
    https://drive.google.com/file/d/1L6bv6iFOga92KcAzb-axSnAYvO0-fwUk/view?usp=sharing
    https://drive.google.com/file/d/1oErnCSKS6Z2R7NR41m0f8Ew8ZPDjHdH2/view?usp=sharing
3. Play the file `Big Buck Bunny_no-opengop.mkv`, skip ahead a minute or two, then stop playback.
4. Try resuming playback of the file from its saved position: 
    ->Playback resumes as it should.
6. Repeat steps 3 & 4 with the file `Big Buck Bunny_opengop.mkv` :
    ->You get no video. Audio plays fine though.

As a workaround, disabling HW acceleration and overclocking the RPi does the trick for me. When overclocked, 1080p videos play smooth for me without HW acceleration. Without overclocking, playback can get a bit choppy with some files.

### Informations
 - LE Version: 10.0.2 & 11.x nightly
 - Hardware Platform: RPi4

### Log file
http://ix.io/49rT

**Comment by HiassofT** [comment]
Thanks a lot for your detailed bugreport!

I could reproduce the issue and also get similar behavior when playing with mpv (on RPiOS) or when using ffmpeg --ss if v4l2 HW decoding is enabled.

Interestingly LE9.2.8 (which uses MMAL HW decoding) resumes this file fine (also when using latest RPi firmware).

I've pinged our video decoder guru, I suspect it's something in ffmpeg / v4l2

**Comment by HiassofT** [comment]
We've got a fix for the issue, it should be included in LE11 builds soon. Backport to LE10 needs a bit more work and will (hopefully) follow later
