### ISSUE TITLE
SwapFile

### ISSUE THREAD

**Issue by Nicooo27** [LibreELEC/LibreELEC.tv#6905]
Hello good afternoon, I have problems mounting the swap in LibreElec 10.0.2 with kodi 19. Once I edit and configure the file, after restarting the device I get an error that I cannot mount the Swap. I can do it without problems on older versions with kodi 18.
Thanks a lot.

**Comment by antonlacon** [comment]
What device?

> Once I edit and configure the file,

What file?

**Comment by Nicooo27** [comment]
hello good, the device is a raspberry pi 4 and the file is swap.conf

**Comment by antonlacon** [comment]
What is the content of `/storage/.config/swap.conf`?

**Comment by antonlacon** [comment]
Github removes attachments when responding via email.

**Comment by heitbaum** [comment]
Closing as inactive. Please reopen if still and issue and with required information.
