### ISSUE TITLE
[BUG] screen flash while watching

### ISSUE THREAD

**Issue by lbarmen** [LibreELEC/LibreELEC.tv#6929]
### Describe the bug
https://www.youtube.com/watch?v=md_fkJDtu1Q
Such a flash occurs every 5-10 minutes, it makes it very difficult to watch

### To Reproduce
I use the elementum plugin and pre-download the movie

### Informations
 - LE 10.2, LE night LibreELEC-RPi4.arm-10.0-nightly-20220919-8c72424 (LE 10.1 this problem does not exist)
 - RPi4 4GB ram
 
### Log file
log file will be added later

**Comment by lbarmen** [comment]
![Screenshot_20220925-175151_Gallery](https://user-images.githubusercontent.com/22907206/192150051-afe34e04-59d4-4dfa-b088-c00f5cad3139.jpg)

**Comment by lbarmen** [comment]
[kodi.log](https://github.com/LibreELEC/LibreELEC.tv/files/9641183/kodi.log)

**Comment by HiassofT** [comment]
Your kodi log shows you are using banned addons.

Remove these addons (ideally reproduce it with a complete clean LE installation) and then either use "pastekodi" on the command line or the log upload function of LE settings to post a log.

**Comment by HiassofT** [comment]
Closing as banned addons are present and no new logs were provided.

Create a new issue if the issue persists with a clean LE installation
