### ISSUE TITLE
Cannot mount NFSv4 volume during init

### ISSUE THREAD

**Issue by anch2150** [LibreELEC/LibreELEC.tv#6958]
I was trying PXE boot on a raspberry pi 4 using `20220929.nightly` build. DHCP and TFTP both worked well. Then the `init` script failed at `mount_flash`. I could manually mount both flash and storage volumes from debug console, though:
```
# mount -t nfs4 <NFS_SERVER_IP>:/libreelec/boot /flash
Works!

# mount -t nfs <NFS_SERVER_IP>:/libreelec/boot /flash
Error -> `Protocol not supported`
```

Is there any way to adjust the hardcoded `fs_type` parameter in `init`?

https://github.com/LibreELEC/LibreELEC.tv/blob/36dcdfdc8b9b1de48fa794edf1289248a875abfc/packages/sysutils/busybox/scripts/init#L206

Thanks!!

My cmdline.txt
```
ip=dhcp boot=NFS=<NFS_SERVER_IP>:/libreelec/boot disk=NFS=<NFS_SERVER_IP>:/libreelec/storage toram
```

**Comment by mglae** [comment]
Use the nfs mount option `vers=[2|3|4|4.0|4.1|4.2]`

```
ip=dhcp boot=NFS=<NFS_SERVER_IP>:/libreelec/boot,vers=4.2 disk=NFS=<NFS_SERVER_IP>:/libreelec/storage,vers=4.2 toram
```

**Comment by anch2150** [comment]
Many thanks! Works like a charm.
