### ISSUE TITLE
[Issue] Nightly builds for 10.0 not created

### ISSUE THREAD

**Issue by lomion0815** [LibreELEC/LibreELEC.tv#6959]
### Describe
The last nightly build for RPi is from "2022-09-25 13:45" while there have been commits on this branch in the days aince. Please check why these builds are not created.

**Comment by heitbaum** [comment]
Nightlies are presently building. https://github.com/LibreELEC/actions/actions/runs/3172451087
Generic is there, others should be there in a few hours.

please reopen if an issue
