### ISSUE TITLE
[BUG] FAILURE: scripts/install lirc:target has failed!

### ISSUE THREAD

**Issue by nvdias0** [LibreELEC/LibreELEC.tv#6980]
### Describe the bug
After today source update (git pull).
When rebuild source from master branch for LE11
got the error:
FAILURE: scripts/install lirc:target has failed!

### To Reproduce
```
git pull
PROJECT=RPi DEVICE=RPi4 ARCH=arm make image
```

### Informations
 - LE Version: [11]
 - Hardware Platform: [RPi4]

### Log file
as the log file is to big for pastebin,
i place here the last lines:

```
*********** FAILED COMMAND ***********
cp -PRf "${SYSROOT_PREFIX}"/* "${PKG_ORIG_SYSROOT_PREFIX}"
**************************************
*********** FAILED COMMAND ***********
${SCRIPTS}/build "${1}" "${PARENT_PKG}"
**************************************
FAILURE: scripts/install lirc:target has failed!

The following log for this failure is available:
  /development/LibreELEC/LibreELEC.tv/build.LibreELEC-RPi4.arm-11.0-devel/.threads/logs/221.log

>>> lirc:target seq 221 >>>
[266/280] [FAIL] install lirc:target

The following log for this failure is available:
  /development/LibreELEC/LibreELEC.tv/build.LibreELEC-RPi4.arm-11.0-devel/.threads/logs/221.log

Parallel build failure - see log for details. Time of failure: Sat Oct  8 16:02:49 WEST 2022
make: *** [Makefile:10: image] Error 1

```

the full log is here:
https://mega.nz/file/cPJV3KRB#njY5Of7NucRaEVefKDbPWDFs7eMBRif2QxlaX-istVE

### Additional context
I've tried to disable lirc module in:
projects/RPi/devices/RPi4/linux/linux.aarch64.conf
by changing 
` CONFIG_LIRC=y
`to
` CONFIG_LIRC=n
`but getting the same result

**Comment by HiassofT** [comment]
Do a clean build
