### ISSUE TITLE
[BUG] Playing stream file fails with 403 error only on Raspberry Pi 4. 

### ISSUE THREAD

**Issue by Zippy457** [LibreELEC/LibreELEC.tv#7001]
### Describe the bug
Playing stream file fails with 403 error only on Raspberry Pi 4.

 Pi 3 and X86_64 platforms with the same build play without any problem.

### To Reproduce
Create .strm file in the Videos folder with the following contents:
    http://89.187.175.143:80/3084/mpegts
From the main menu, select Videos > Media sources - Videos > click in the name of the .strm file created above.

### Informations
LibreELEC 10.0.2 - Kernel Linux 5.10.76  on a Raspberry Pi 4

Build: 19.4(19.4.0)

Git; 19.4-Matrix

Compiled: 2022-03-05

### Log file
 https://pastebin.com/9tv9JpyX

### Additional context
 Pi 3 and X86_64 platforms with the same build play without any problem.
Also tried playing URL on a Windows machine using VLC without any problems.
Using Curl at the command line with this URL on the RasPi4 seems to work ok as well.
I created a fresh install with a new SD card and had the same result.

**Comment by HiassofT** [comment]
Use the forum for support requests
