### ISSUE TITLE
vcgencmd display_power doesn't work

### ISSUE THREAD

**Issue by waynethomas69** [LibreELEC/LibreELEC.tv#7018]
### Describe the bug
since upgrading from LE 10.0.2 to LE 10.0.3 on my RPi 3b, the Turn Off screensaver stopped working. This was set to "No Signal on Raspberry Pi (using vcgencmd)". Using ssh I have tried issuing the "vcgencmd display_power" command, and it has no effect - no errors, just keeps returning "display_power=1" without ever toggling to off.

### To Reproduce
1. Initiate Turn Off screensaver set to "No Signal on Raspberry Pi (using vcgencmd)" or issue ""vcgencmd display_power" at the command line.
2. Nothing happens

### Informations
 - LE Version: 10.0.3
 - Hardware Platform: RPi3

### Log file
No errors are issued, it just fails to do anything

**Comment by HiassofT** [comment]
This is expected as LE10 switched from the legacy display drivers to the standard linux kms display driver stack.

hdmi options in config.txt and all the proprietary, legacy commands like tvservice/vcgencmd/... don't work anymore

**Comment by waynethomas69** [comment]
Weird, vcgencmd still worked in LE 10.0.2 - it was only the shift to 10.0.3 that caused it to stop working.
Unfortunately DPMS doesn't seem to work properly so need to find an alternate way to stop the display signal.

**Comment by lazou** [comment]
@waynethomas69 Did you found a working alternative method to turn off & on the display like it was possible with `vcgencmd`? Looks like `xset` or `xrandr` are not shipped with LibreELEC. The only solution I found so far was `kodi-send --action='ToggleDPMS'`. But I want to explicetly switch on or off, not only toggling.

**Comment by waynethomas69** [comment]
@lazou I couldn't get it to work (even the toggle DPMS route) so employed a smart switch with my home automation and modified the addon to switch that on and off instead
