### ISSUE TITLE
[BUG] addon service.emby4 required sqlite 3.35.0+ if bootstrap with version v4.7.8.0

### ISSUE THREAD

**Issue by ihipop** [LibreELEC/LibreELEC.tv#7021]
### Describe the bug
https://emby.media/community/index.php?/topic/111848-dlna-configuration-profile-error/&do=findComment&comment=1188913

### Informations
 - LE Version: 10.0.3
 - Hardware Platform: nanopc-T4

## Suggest solutions
- open a PR to [backport SQLITE 3.35.0+](03227b593179ca617540f0aced8a253fa7deb367) to LE Version: 10.0 ,which I've tested on my device
- bundle a sqlite library to service.emby4 addon 
- lock the emby version of LE Version: 10.0  to v4.7.6.0

which one do you prefer ? @heitbaum

**Comment by heitbaum** [comment]
Hi @ihipop - with LE10 now final. And LE11 with Kodi20 just around the corner - and supporting emby. I’ll close this as a known issue.
