### ISSUE TITLE
[BUG] 64x64 album cd cover for librespot

### ISSUE THREAD

**Issue by diegombeltran** [LibreELEC/LibreELEC.tv#7063]
### Describe the bug
librespot addon downloads small small album thumbnail from Spotify CDN. Cached album cd art is 64x64, which shows very blurry on skins like Aeon Nox Silvo or Artic Zephy Reloaded.

### To Reproduce
Using Aeon Nox Silvo or Artic Zephyr Reloaded and Artist Slideshow add-on with librespot. 

### Informations
 - LE Version: 10.0.2
 - librespot add-on version: latest
 - Hardware Platform: RPi4

### Log file
http://ix.io/4evV

### Additional context
It was working some months ago. Maybe related to [this issue](https://github.com/librespot-org/librespot/issues/972) where Spotify chaning their CDN is pointed.

**Comment by heitbaum** [comment]
Closing - new version of librespot added. Please retest and reopen if still an issue
- #7732
