### ISSUE TITLE
[BUG] v3d fec00000.v3d: MMU error from client CLE (4) at 0x6801000, pte invalid

### ISSUE THREAD

**Issue by ejsc1** [LibreELEC/LibreELEC.tv#7067]
### Describe the bug
dmesg:
[ 7688.934184] v3d fec00000.v3d: MMU error from client CLE (4) at 0x6801000, pte invalid

### To Reproduce
1. Update to **LibreELEC (community): nightly-20221030-111579e (RPi4.arm)**
2. Write in console: # dmesg

### Informations
 - LE Version: nightly-20221030-111579e (RPi4.arm)
 - Hardware Platform: RPi4

### Log file
[dmesg_nightly-20221030-111579e .txt](https://github.com/LibreELEC/LibreELEC.tv/files/9896833/dmesg_nightly-20221030-111579e.txt)

### uname -a
Linux LibreELEC 6.0.5 #1 SMP Sun Oct 30 04:46:38 UTC 2022 aarch64 GNU/Linux

**Comment by chewitt** [comment]
See https://github.com/raspberrypi/linux/issues/4434#issuecomment-874527310 .. and please check the Pi kerrnel repo before opening more tickets (it's the better location for Pi kernel issues). Closing here.
