### ISSUE TITLE
Add support for Logitech Keyboards (solaar?)

### ISSUE THREAD

**Issue by ejsc1** [LibreELEC/LibreELEC.tv#7081]
Hello,

Example: Logitech K600 TV - Without solaar not all the Fn keys work
https://www.logitech.com/en-us/products/keyboards/k600-smart-tv-d-pad.920-008822.html

Solaar:
https://github.com/pwr-Solaar/Solaar

Thanks

**Comment by HiassofT** [comment]
Please use the forum for feature requests
https://forum.libreelec.tv/board/18-feature-requests/
