### ISSUE TITLE
[BUG] dosbox on rock64: <shift>-key not working as expected

### ISSUE THREAD

**Issue by chri2** [LibreELEC/LibreELEC.tv#7100]
### Describe the bug

Started dosbox from the add-on menu and got the prompt. mounted a directory as c:. Wanted to change to c: and couldn't enter the `:`.

The shift keys on two keyboards (wireless, usb) I tried behave like this: I can enter upper letters. But I can't enter any symbols like <shift>-<6>, or <shift>-<.>.

This makes it impossible (at least I didn't find a way) to e.g. change the drive by `cd c:`.

### To Reproduce

1. install dosbox
2. start dosbox from the add-on menu
3. connect wireless usb keyboard
4. try to type a `:` or a `&`

### Informations

 - LE Version: 10.0.3
 - Hardware Platform: Rock64 with soundboard

### Log file

nothing logged when a not-working key is pressed

### Additional context

I also tried to change the keyboard layout to the one my hardware provides by `keyb gr` and tried the function for mapping keys to map the shift keys. Didn't help.

**Comment by heitbaum** [comment]
Please retest with le11/le12. A large number of updates have been made with emulation. Please reopen with updated details - if still an issue.
