### ISSUE TITLE
[BUG] Screensaver shows no pictures from NFS folder

### ISSUE THREAD

**Issue by magicWF** [LibreELEC/LibreELEC.tv#7178]
### Describe the bug
Since the last update to the current LibreELEC-RPi2.arm-11.0-nightly from a version of October, the screensaver for a gallery view does not show any picture. Before the update it's work.
As picture source for the screensaver is NFS device selected.

### To Reproduce
1. Enable the photo gallery screen saver
2. select a NFS source for the photos
3. test screensaver or wait for automagically start.

### Informations
 - LE Version: LibreELEC-RPi2.arm-11.0-nightly-20221126
 - Hardware Platform: PRI3

**Comment by HiassofT** [comment]
closing as no log file provided. please use the forum for support questions
