### ISSUE TITLE
[BUG] complete freezing during movie TV or series watching -pulse eight CEC issue-?

### ISSUE THREAD

**Issue by goofy84** [LibreELEC/LibreELEC.tv#7240]
I think my pluse eight usb cec adapter is causing these freezes. My hardware:
kodi matrix 10.0002 libreelec on a x86 PC, pulse eight adapter usb flashed with firmware 4.
Board Asrock h110tm R2.o
2 ssds
1 sundtek stick 
Thanks in advance
[kodi.log](https://github.com/LibreELEC/LibreELEC.tv/files/10208554/kodi.log)
[kodi_crashlog_20221211173500.log](https://github.com/LibreELEC/LibreELEC.tv/files/10208555/kodi_crashlog_20221211173500.log)

**Comment by heitbaum** [comment]
Please confirm if this is still an issue with LE11/LE12 nightlies, please reopen with updated info/create a new issue referencing this one.
