### ISSUE TITLE
[BUG]HDR10+ files outputting rec709

### ISSUE THREAD

**Issue by atoulmin** [LibreELEC/LibreELEC.tv#7261]
So I know libreelec doesn’t support dynamic metadata that’s fine. However HDR10+ files should be outputted at BT2020 not Rec709. 

That way we can still play the files and get correct colours regardless of the dynamic metadata. 

If we detect HDR10+ files. We should force BT2020 colourspace. 

HDR10+ is backwards compatible with HDR10

https://paste.kodi.tv/yefikoqefu

**Comment by HiassofT** [comment]
Use the forum for feature requests - also very likely this isn't a LibreELEC issue but a kodi issue
