### ISSUE TITLE
[BUG] Kodi restarts at the beginning

### ISSUE THREAD

**Issue by ejsc1** [LibreELEC/LibreELEC.tv#7269]
### Informations
 - LE Version: LibreELEC-RPi4.arm-11.0-nightly-20221217-9f64444.img.gz
 - Hardware Platform: RPi4

**Comment by HiassofT** [comment]
you didn't read the forum-wide announcement, did you?
https://forum.libreelec.tv/thread/26357-attention-le11-nightly-2022-12-08-will-cause-issues-with-binary-addons/
