### ISSUE TITLE
[BUG] kodi crashes on video start when using mysql database on pi4 and version 11

### ISSUE THREAD

**Issue by evilbulgarian** [LibreELEC/LibreELEC.tv#7286]
### Describe the bug
When I play any video kodi will crash if I have my advanced settings pointing to a mysql db:
with or without blow settings set to true or false
```
<importwatchedstate>true</importwatchedstate>
<importresumepoint>true</importresumepoint>
```

### To Reproduce
1. Play any video
2. Kodi crashes and restarts

### Informations
 - LE Version: LibreELEC-RPi4.arm-11.0-nightly-20221221-d479071.img.gz (sha256) 
 - Hardware Platform: Rpi4

### Log file
[kodi_crashlog_20221222202822.log](https://github.com/LibreELEC/LibreELEC.tv/files/10292097/kodi_crashlog_20221222202822.log)

**Comment by HiassofT** [comment]
Closing as you have banned adons installed https://kodi.wiki/view/Official:Forum_rules/Banned_add-ons

Open a new issue if the problem exists on a clean LibreELEC installation
