### ISSUE TITLE
[BUG] Orange Pi 3 Fail to boot "Could not mount UUID=..."

### ISSUE THREAD

**Issue by paulsykes** [LibreELEC/LibreELEC.tv#7287]
### Describe the bug
Nightly builds for Orange Pi 3 will not boot from SD Card.

The last working nightly build is LibreELEC-H6.arm-11.0-nightly-20221007-bbb8c6b-orangepi-3.img.gz.  

All builds from LibreELEC-H6.arm-11.0-nightly-20221008-1d2cd1d-orangepi-3.img.gz to present are effected.  

The following error message is displayed at boot on all builds.
```
*** Error in mount_flash: mount_common: Could not mount UUID=0810-1828 
### Starting debugging shell for boot step: mount_flash... type exit to quit ###
```

### To Reproduce
1. Write any nightly build to SD from and after 20221008-1d2cd1d and attempt to boot.

### Informations
 - LE Version: Nightly devel
 - Hardware Platform: Orange Pi 3

EMMC is stock as shipped by Orange Pi with no changes. Hardware is stock as shipped by Orange Pi with no changes.

**Comment by heitbaum** [comment]
- see #8099
