### ISSUE TITLE
Docker Addon not working on iMX6

### ISSUE THREAD

**Issue by sm4rty-github** [LibreELEC/LibreELEC.tv#7303]
Hello,
the Docker Deamon isnt able to start on iMX6 Devices with LE 11 latest build from dec. 25

Dec 27 15:14:20 LibreWBQ dockerd[1405]: failed to start daemon: Error initializing network controller: error obtaining controller instance: failed to create NAT chain

it asks if nat module is inserted

but insmod nat doesnt do the job for me.

what to do?

**Comment by heitbaum** [comment]
> Hello, the Docker Deamon isnt able to start on iMX6 Devices with LE 11 latest build from dec. 25
> 
> Dec 27 15:14:20 LibreWBQ dockerd[1405]: failed to start daemon: Error initializing network controller: error obtaining controller instance: failed to create NAT chain
> 
> it asks if nat module is inserted
> 
> but insmod nat doesnt do the job for me.
> 
> what to do?

When was the last time it worked for you?

I haven’t tested running docker on the cubox (if ever/for a while)
- it looks like NF_NAT kernel configs are missing from the iMX6 config.
- I haven’t run tested #7304 but it should fix your error.
