### ISSUE TITLE
Nvidia driver not loading on latest nightly

### ISSUE THREAD

**Issue by RenEH01** [LibreELEC/LibreELEC.tv#7323]
Libreelec hangs on Libreelec logo not loading the graphics driver on 12/30/2022 nightly and 12/29/2022 nightly. 

Share folders are still present and OS appears to be running fine otherwise. 

Graphics card is gt1030.

**Comment by SupervisedThinking** [comment]
Which nightly did you use? Generic or Generic-Legacy?

**Comment by RenEH01** [comment]
Generic, is this card now considered legacy?

**Comment by SupervisedThinking** [comment]
You have to use those images for NVIDIA GPUS https://test.libreelec.tv/11.0/Generic/Generic-legacy/ since they use X11 instead of GBM

**Comment by RenEH01** [comment]
Doesn't the newer Nvidia drivers support GBM as of 495.44?

**Comment by SupervisedThinking** [comment]
It does support GBM+Wayland but it doesn't work without a displayserver, NVIDIA users have to stick to Generic-Legacy for now.

**Comment by RenEH01** [comment]
> It does support GBM+Wayland but it doesn't work without a displayserver, NVIDIA users have to stick to Generic-Legacy for now.

Thanks for the info!
