### ISSUE TITLE
10.0.2 nvidia hevc sw

### ISSUE THREAD

**Issue by liujixu1984** [LibreELEC/LibreELEC.tv#7327]
My version is 10.0.2, and the video card is nvidia 1080. Why can't I hard understand the Hevc code? Screen display sw
![IMG_20230101_134359](https://user-images.githubusercontent.com/47080366/210162202-b0625c6b-75a3-4812-90f0-e857b0f7b71d.jpg)
![IMG_20230101_134445](https://user-images.githubusercontent.com/47080366/210162205-4db70515-dd77-47c9-8da0-f5a6d70d21ee.jpg)

**Comment by liujixu1984** [comment]
I have tried version 10.0.3 and several versions of nightly build, but they cannot be started


![Screenshot_2023-01-01-13-49-46-373_org connectbot](https://user-images.githubusercontent.com/47080366/210162232-b22c0f3d-6adc-484a-9e6e-095a661c848a.png)

**Comment by atoulmin** [comment]
I don’t think NVIDIA is supported on generic. You have to use generic legacy. Give that a go.

**Comment by liujixu1984** [comment]
> I don’t think NVIDIA is supported on generic. You have to use generic legacy. Give that a go.

I have used 10.0.2 and 9. x versions, and the results are the same. Can you provide an address for me to download and test!

**Comment by atoulmin** [comment]
Try this build

https://test.libreelec.tv/11.0/Generic/Generic-legacy/LibreELEC-Generic-legacy.x86_64-11.0-nightly-20221231-b9ea43f.img.gz

**Comment by liujixu1984** [comment]
> 试试这个版本
> 
> https://test.libreelec.tv/11.0/Generic/Generic-legacy/LibreELEC-Generic-legacy.x86_64-11.0-nightly-20221231-b9ea43f.img.gz

My machine cannot be started in this version. See Figure
![IMG_20230101_204215](https://user-images.githubusercontent.com/47080366/210171059-22ef4a2b-457e-4f6b-b6df-d91de240b114.jpg)

**Comment by lrusak** [comment]
Please use the forum for support. This is a bug tracker.

https://forum.libreelec.tv/
