### ISSUE TITLE
[BUG] RPi4 Screensaver Turn Off via CEC no longer works since 10.0.4

### ISSUE THREAD

**Issue by makuser** [LibreELEC/LibreELEC.tv#7510]
### Describe the bug

Turning off monitor via CEC no longer works since latest update to 10.0.4

### To Reproduce
1. Set up screen saver 'Power Off'
2. Set display method to CEC
3. Start preview or wait for screensaver to kick in normally

### Informations
 - LE Version: 10.0.4
 - Hardware Platform: RPi4

### Additional context

Was working on last few releases

**Comment by heitbaum** [comment]
Please retest with latest (nightly) LE11, if still an issue - please reopen this issue, or create a new issue referencing this one.
