### ISSUE TITLE
[BUG] Disabled hibernate(s4) broke wake up from RTC event.

### ISSUE THREAD

**Issue by hetii** [LibreELEC/LibreELEC.tv#7511]
According thread:

https://forum.libreelec.tv/thread/12414-enable-hibernate-x86-plattform/
and commit:
https://github.com/LibreELEC/LibreELEC.tv/commit/4d479bc6a7a8719efbe7eddaea6dfcdab63f3234

Hibernate (s4) support is removed from current builds.
 
The issue here is in that many boards use S4 to be able to wake up on RTC events, 
so things like scheduling PVR in tvheadend and wake up before recording, are no longer possible.

I think that this option should be enabled back and the end user should decide if need it or not, as it was so far.

Best Regards.

**Comment by heitbaum** [comment]
Closing as not bug. Feature in-place since 2010. Last discussed in 2018.
