### ISSUE TITLE
[BUG]after update boot fails with Failed to start openvpn.service message

### ISSUE THREAD

**Issue by Greygeek2** [LibreELEC/LibreELEC.tv#7537]
### Describe the bug
I have used LibreELEC for years, and just updated the program from 10 to 11, not fully realizing the 11 was in beta.  Once updated I only load to the splash screen with the above error message.
I then downloaded 10.95.1 and reinstalled fresh to solve the problem, but the same error message haunts me.  In the past the error message would appear, but would not stop the loading process.

### To Reproduce
1. Turn on the unit
2 See error

### Informations
 - LE Version: 10.95.1
 - Hardware Platform: HTPC

### Log file
I do not know how to provide log file if the program does not run

**Comment by chewitt** [comment]
Please use the form for support. Read https://wiki.libreelec.tv/support/log-files for info on generating logs (before you share them in the forum).
