### ISSUE TITLE
[BUG] CONFIG_NFS_DISABLE_UDP_SUPPORT=y kernel flag preventing mounting of NFS UDP Shares

### ISSUE THREAD

**Issue by Codicier** [LibreELEC/LibreELEC.tv#7670]
### Describe the bug
Unable to mount NFS shares on LE using the `mount -o udp` option, due to this functionality being disabled by a kernel flag.

### To Reproduce
Access commandline of LE installation
`mount -t nfs <server nfs share path> <client path> -o udp`
`mount: mounting <server nfs share path> on <client path> failed: Invalid argument`

### Information
 - LE Version: 11.0.0
 - Hardware Platform: RPi4

### Additional context
Link to the [commit](https://github.com/LibreELEC/LibreELEC.tv/commit/fa9baeb41498541f4215980967fe368a21956b64#diff-f465060c3ffd49e3697c08555667fb97d7fdda4313d5b1e4086907d5b40247d3R5710) (and specific line number) which carried this kernel flag into LE.

Requesting this kernel flag be removed in a future update so that this option is available once again for users that wish to make use of it.

**Comment by HiassofT** [comment]
NFS over UDP is disabled on linux kernels by default as it's known to lead to data corruption. See eg the help text of that kernel option
https://github.com/raspberrypi/linux/blob/rpi-5.15.y/fs/nfs/Kconfig#L200-L207
```
config NFS_DISABLE_UDP_SUPPORT
       bool "NFS: Disable NFS UDP protocol support"
       depends on NFS_FS
       default y
       help
	 Choose Y here to disable the use of NFS over UDP. NFS over UDP
	 on modern networks (1Gb+) can lead to data corruption caused by
	 fragmentation during high loads.
```
I'm closing this as we don't plan to enable this rather dangerous option and other distrubutions like Debian have UDP disabled, too. Use NFS over TCP instead
