### ISSUE TITLE
[BUG] Build failure of inputstream.ffmpegdirect 

### ISSUE THREAD

**Issue by heitbaum** [LibreELEC/LibreELEC.tv#7672]
### Describe the bug

Build failure of inputstream.ffmpegdirect 

### To Reproduce
Build inputstream.ffmpegdirect 20.5.0

### Informations
 - LE Version: LE12
 - Hardware Platform: All

### Log file

```
/build/build.LibreELEC-ARMv7.arm-12.0-devel/build/inputstream.ffmpegdirect-20.5.0-Nexus/src/stream/FFmpegStream.cpp: In member function 'virtual std::string ffmpegdirect::FFmpegStream::GetStreamCodecName(int)':
/build/build.LibreELEC-ARMv7.arm-12.0-devel/build/inputstream.ffmpegdirect-20.5.0-Nexus/src/stream/FFmpegStream.cpp:2073:42: error: invalid conversion from 'const AVCodec*' to 'AVCodec*' [-fpermissive]
 2073 |     AVCodec* codec = avcodec_find_decoder(stream->codec);
      |                      ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~
      |                                          |
      |                                          const AVCodec*
ninja: build stopped: subcommand failed.
FAILURE: scripts/build inputstream.ffmpegdirect:target during make_target (default)
```
### Additional context

[build.LibreELEC-Generic-legacy.x86_64-12.0-devel-inputstream.ffmpegdirect_target-479.log](https://github.com/LibreELEC/LibreELEC.tv/files/11012687/build.LibreELEC-Generic-legacy.x86_64-12.0-devel-inputstream.ffmpegdirect_target-479.log)

**Comment by HiassofT** [comment]
inputstream.ffmpegdirect hasn't been update to ffmpeg 5+  so this is an upstream bug - fix for LE will be to update to a fixed upstream version when it's available

**Comment by lrusak** [comment]
> inputstream.ffmpegdirect hasn't been update to ffmpeg 5+  so this is an upstream bug - fix for LE will be to update to a fixed upstream version when it's available

In the Omega branch there is ffmpeg 5.x support.

**Comment by HiassofT** [comment]
There's no Omega tag yet and even worse the version in addon.xml is still at the current Nexus release (20.5.0). So we can't pull in HEAD of the Omega branch as that'll create a version mess.

As soon as an Omega release gets tagged our update script will pick up the new version and this issue can be fixed.

**Comment by lrusak** [comment]
> There's no Omega tag yet and even worse the version in addon.xml is still at the current Nexus release (20.5.0). So we can't pull in HEAD of the Omega branch as that'll create a version mess.
> 
> 
> 
> As soon as an Omega release gets tagged our update script will pick up the new version and this issue can be fixed.

All you have to do is ask. https://github.com/xbmc/inputstream.ffmpegdirect/pull/233

**Comment by heitbaum** [comment]
> > There's no Omega tag yet and even worse the version in addon.xml is still at the current Nexus release (20.5.0). So we can't pull in HEAD of the Omega branch as that'll create a version mess.
> > As soon as an Omega release gets tagged our update script will pick up the new version and this issue can be fixed.
> 
> All you have to do is ask. [xbmc/inputstream.ffmpegdirect#233](https://github.com/xbmc/inputstream.ffmpegdirect/pull/233)

Thanks - PR merged 👍
