### ISSUE TITLE
[BUG] Build errors of aarch64 game.libretro. and libretro.

### ISSUE THREAD

**Issue by heitbaum** [LibreELEC/LibreELEC.tv#7673]
### Describe the bug

Build errors of aarch64 game.libretro. and libretro. in aarch64

### To Reproduce
build the following addons:
- game.libretro.beetle-pcfx
- game.libretro.mame2000
- game.libretro.mame2010
- game.libretro.pcsx-rearmed
- game.libretro.yabause

### Informations
 - LE Version: LE12
 - Hardware Platform: aarch64 userland

### Log file

- https://github.com/LibreELEC/actions/suites/11656508629/artifacts/605848696
- https://github.com/LibreELEC/actions/actions/runs/4458722941#artifacts

### Additional context

![image](https://user-images.githubusercontent.com/6086324/226221201-4895c8a0-1a13-4fe8-be0b-137372ccda76.png)

**Comment by HiassofT** [comment]
Any retroplayer related issues in LE12 are currently on hold until we find a solution how we can maintain them in the future - ideally by the game.libretro binary addons provided from a kodi repo
