### ISSUE TITLE
[Suggestion] no change of hosts.conf by python script

### ISSUE THREAD

**Issue by ajbathe** [LibreELEC/LibreELEC.tv#7674]
Would it be possible to change /usr/config/hosts.conf to
[usr-config-hosts.conf.txt](https://github.com/LibreELEC/LibreELEC.tv/files/11017129/usr-config-hosts.conf.txt)
and not changing it by hostname.py from the addon service.libreelec.settings anymore?
[service.libreelec.settings-resources-lib-hostname.py.patch.txt](https://github.com/LibreELEC/LibreELEC.tv/files/11017144/service.libreelec.settings-resources-lib-hostname.py.patch.txt)

**Comment by ajbathe** [comment]
Sure:

1st reason: If an administrator creates or changes /storage/.config/hosts.conf, this configuration shouldn't be changed or touched by a machine. You get angry if you see some change which is - by the way - wrong. My philosophy is: If a human does some configuration, some auto-mechanism shouldn't change that. Do you agree?

So we come to that 2nd reason:

It is well known, that an entry in /etc/hosts is that way:
192.168.0.3 libreelec.mynetwork libreelec
and not
192.168.0.3 libreelec libreelec.mynetwork

The sequence is IP - FQDN - (short) HOSTNAMES. Please google that or see, e.g. https://wiki.scn.sap.com/wiki/pages/viewpage.action?pageId=585106840 - or see [RFC 952](https://tools.ietf.org/html/rfc952).

The python script hostname.py adds the hostname to the ip 127.0.0.1 which is also wrong. This is only the IP of localhost.

And - because I'm lazy too, - I don't want to add my (corrected) service.libreelec.settings-addon after some installation anymore ;-)

**Comment by ajbathe** [comment]
@chewitt
could I bring https://github.com/LibreELEC/LibreELEC.tv/pull/7696#issuecomment-1486341135 to your attention ?
-> "The addon's code [ano service.librelec.settings] doesn't live in this repo. Changes need to be made here first."

**Comment by heitbaum** [comment]
Closing as completed. Please reopen with updated information if still an issue.
