### ISSUE TITLE
[BUG] When I try to connect to wifi reports "invalid-key" on Asus TinkerBoard (RK3288)

### ISSUE THREAD

**Issue by rgabbo** [LibreELEC/LibreELEC.tv#7678]
### Describe the bug

When I try to connect to my wifi, it fails with the error “invalid-key”. I'm sure the key is correct.

### To Reproduce

1. Go to 'LibreELEC'
2. Go to 'Connections'
3. Try to connect to wifi
4. See the message "invalid-key"

### Informations

- LE Version: 11.0.0
- Hardware Platform: ASUS TinkerBoard

### Log file

Unable to follow the steps cause I can't connect to the internet

**Comment by Freedom42082** [comment]
I have the same issue.

Informations

LE Version: 11.0.0
Hardware Platform: Rasberry Pi 4b 8-gig

**Comment by Sebazzz** [comment]
Related: #7166

**Comment by heitbaum** [comment]
Please retest with iwd2.4 - LibreELEC-yyyyy-11.0-nightly-20230329-a0f002b.img.gz (or newer) from https://test.libreelec.tv/11.0

**Comment by chewitt** [comment]
I'm closing this ticket as the main discussion is taking place in #7166 - please follow up there.
