### ISSUE TITLE
Issue with pvr.iptvsimple: update 21.2.0-Omega to 21.2.1-Omega

### ISSUE THREAD

**Issue by newf276** [LibreELEC/LibreELEC.tv#7695]
Don't think it is necessary to include logs etc.

Simple issue I believe, as it is not an issue with pvr.iptvsimple: update 21.2.0-Omega to 21.2.1-Omega, it is the dependancies, which for some reason look for version 0.0.0.0 for input.adaptive, because there is no such version.

Please fix dependancies versions for pvr iptv simple, for generic x86 Libreelec.

**Comment by HiassofT** [comment]
I disagree. If you want to report issues you have to provide logs and the whole issue template filled out - you didn't even mention which platform/device you are using , so I'm closing this.

Feel free to create a new bug report when you've changed your mind and think you can agree to our requirements.
