### ISSUE TITLE
[BUG] build failure on Openssl 

### ISSUE THREAD

**Issue by A1RF0RCE1** [LibreELEC/LibreELEC.tv#7713]
### To Reproduce
Just compile from source 
PROJECT=RPi DEVICE=RPi4 ARCH=arm BUILDER_NAME=dev-latest make image

### Informations
 - LE Version: 12
 - Hardware Platform: RPi4

### Log file

https://pastebin.com/YYwg7c4x

### note 
sha key of package procps-ng is incorrect.

**Comment by heitbaum** [comment]
Building arm is failing aarch64 working. Upstream patch included in PR.
