### ISSUE TITLE
MISUSE of administration power of LE-forum-moderator

### ISSUE THREAD

**Issue by ajbathe** [LibreELEC/LibreELEC.tv#7723]
Hello everybody,

I want to point out, that I was banned at LE-forum today just because I linked to a wikipedia article on CENSORSHIP. No personal comment, only one simple hyperlink to https://en.wikipedia.org/wiki/Censorship not public, but as a personal message to that guy who closed a thread with "too much trash".

The reason for that was the thread about the WiFi-issue of LE10+ till today, which was abruptly closed by a moderator who IMHO is not empowered or suitable to do this responsible task. There was no warning before at the guys who wrote about "the mighty people" there. This thread was closed immediately and now I can't and I don't want to deliver my abilities to people anymore who are not able to write a simple but correct hostfile.

I point out, that there are other projects like OSMC e.g.

I am banned now without any reason. The reproach of  "Visual attack against moderator." is ridiculous. People here are misusing their administration forces. Free speech is suppressed!

https://forum.libreelec.tv/thread/26761-invalid-wifi-key/?postID=179090#post179090

**Comment by HiassofT** [comment]
This issue tracker is for reporting bugs in LibreELEC so I'm closing this

**Comment by ajbathe** [comment]
As long as it won't be deleted, I don't care. Yes, I reported a big social bug within your LE-team. And it is the only way I can do it. What would you say, when you wanted to login a forum and you see what I described? Would you be happy?
