### ISSUE TITLE
BPIM5 - Can't boot Libreelec 11 because cannot mount SYSTEM

### ISSUE THREAD

**Issue by sosie-js** [LibreELEC/LibreELEC.tv#7733]
### Describe the bug
Boot crashes indicating can not mount SYSTEM

### To Reproduce
Using armbian minimal image to boot and issue these commands

1 - From a Linux machine, prepare a sdcard with armbian
```
wget https://xogium.performanceservers.nl/dl/bananapim5/archive/Armbian_23.02.2_Bananapim5_jammy_current_6.1.11_minimal.img.xz
wget https://github.com/BPI-SINOVOIP/bpi-tools/blob/master/bpi-copy
SDCARD=/dev/sdx #replace sdcard by the device where a fresh sdcard has been inserted)
sudo bash bpi-copy Armbian_23.02.2_Bananapim5_jammy_current_6.1.11_minimal.img.xz $SDCARD 
```
 
2 - From the SBC, ie Bananapi M5, follow the Armbian install process steps
a - Put your sdcard on the slot 
b - Power it on
il will boot on the SDCARD if the Emmc was erased with `dd if=/dev/zero of=/dev/mmcblk1`
You will be asked to give name, password ..

3 - Flash Libreelec into the  EEMC
a - login with the credentials you have given
b - transfert  it to the flash 
```
wget https://ftp.halifax.rwth-aachen.de/libreelec/LibreELEC-AMLGX.arm-11.0.1-bananapi-m5.img.gz
gunzip LibreELEC-AMLGX.arm-11.0.1-bananapi-m5.img.gz
wget https://github.com/BPI-SINOVOIP/bpi-tools/blob/master/bpi-copy
sudo bash bpi-copy LibreELEC-AMLGX.arm-11.0.1-bananapi-m5.img  /dev/mmcblk1    #  Flash EMMC 14,6G  
```

4- Reboot 
` sudo reboot`
  
>> It will  stall in initramfs indicating cannot mount SYSTEM <<
   
### Informations
 - LE Version: AMLGX.arm-11.0.1-bananapi-m5
 - Hardware Platform: Bananapi M5

SOLUTION:
I am lazy to seek where to patch from the source so see [my post](https://forum.armbian.com/topic/27669-making-libreelec-work-on-bananapi-m5-side-by-side-with-armbian-possible/#comment-162881) providing how I fixed the LE Image.

**Comment by chewitt** [comment]
For the record, this is with my current branch(es): https://pastebin.com/raw/sT3GiLa3

I'm not booting the same u-boot or kernel version in the official 11.0.1 image; but zero changed in the "unpack SYSTEM" part of the distro so it's still a valid comparison.
