### ISSUE TITLE
[BUG] empty update list in libreelec 12 on rpi4

### ISSUE THREAD

**Issue by origpumu** [LibreELEC/LibreELEC.tv#7739]
### Describe the bug
There is no entry shown in available Updates for librelec-12.0 channel. 

### To Reproduce
1. Go to settings
2. Libreelec
3. Updates
4. Available updates

### Informations
 - LE Version: nightly-20230331-9bd74ce
 - Hardware Platform: RPi4

### Additional context
I was only able to upgrade to v12 by wgetting update file into .updates. Available updates are Not shown in the list on gui.

**Comment by chewitt** [comment]
Absence of LE12 from the current update data is intentional. Users are welcome to manually update but Kodi Omega is still in a pre-Alpha state and some further core changes are required before we encourage anyone to use nightlies. As there is no bug I'm closing the ticket.
