### ISSUE TITLE
Kodi not listing all supported resolutions/refresh rates

### ISSUE THREAD

**Issue by RenEH01** [LibreELEC/LibreELEC.tv#7775]
### Describe the bug
In the settings tab not all supported resolutions/refresh rates of the TV are listed. TV is a Samsung qn90a. Specifically, 23.98hz, 24hz and 30hz are not listed as available for resolutions below 1080p. Only higher refresh rates i.e. above 50hz are available for 720P and below resolutions. 

### To Reproduce
1. Go to settings
2. Select resolution
3. Lower refresh rates are not available. 

### Informations
 - LE Version: 11.0.1
 - Hardware Platform: RPi4

### Additional context
Very high refresh rate options are available, up to 120hz. TV properly supports lower refresh rates at 720p using other devices.

**Comment by chewitt** [comment]
It is very unlikely there is a bug in Kodi so I'm closing the ticket here. Please create an topic in the LE forum and provide debug/pastekodi logs so the LE staff can follow-up.
