### ISSUE TITLE
[BUG] Addon service.tvheadend42 : In settings, cannot change file PATH when XMLTV Type is FILE

### ISSUE THREAD

**Issue by Salokyn** [LibreELEC/LibreELEC.tv#7776]
### Describe the bug
In addon : service.tvheadend42
Cannot change file PATH when EPG Type is FILE

### To Reproduce
1. Go to plugin settings, in XMLTV part
2. Choose FILE type
3. File path cannot be edited

### Additional context
https://github.com/LibreELEC/LibreELEC.tv/blob/master/packages/addons/service/tvheadend42/source/resources/settings.xml#L8

Should be change in :

```xml
<setting id="XMLTV_LOCATION_FILE" type="file" label="30006" default="" enable="eq(-1,1)"/>
```

**Comment by heitbaum** [comment]
hi @Salokyn - suggest you raise a Pull Request for this update to tv headend 4.2/4.3 and detail around what is being changed. (Could be backported as well)
