### ISSUE TITLE
[BUG] build issue with game.libretro.beetle-psx on Generic-legacy

### ISSUE THREAD

**Issue by heitbaum** [LibreELEC/LibreELEC.tv#7805]
- Proposed upstream fix - https://github.com/kodi-game/game.libretro.beetle-psx/pull/19
- First part of the fix was included in #7792

**Comment by garbear** [comment]
I closed https://github.com/kodi-game/game.libretro.beetle-psx/pull/19. This issue should be closed when beetle-psx-hw is added as a core
