### ISSUE TITLE
Not Possible to register

### ISSUE THREAD

**Issue by Lowrider0** [LibreELEC/LibreELEC.tv#7854]
When I try to register, it says something like "Invalid data".

Also i don't receive an email to activate the account.

**Comment by Lowrider0** [comment]
On Google Chrome, it doesn't work. Edge works. Also on Hotmail i'm not receiving anything (Spam neither). Gmail works.

**Comment by Lowrider0** [comment]
When I click on the activation link, it says: "Already activated."

When I try to login after, it says, "Username unknown".

Guess I've seen enough.

**Comment by CvH** [comment]
Difficult to help without knowing username or email.
