### ISSUE TITLE
[BUG]Black screen on RPI4

### ISSUE THREAD

**Issue by Djej30** [LibreELEC/LibreELEC.tv#7883]
### Describe the bug

At startup, the libreelec logo is displayed, then the kodi nexus logo appears and remains for 1 minute, then the screen goes black.
### Informations
 - LE Version: 11.0.1
 - Hardware Platform: RPI4

**Comment by HiassofT** [comment]
Please use the forum for support.

We need at least log files and detailed info about your TV, setup etc here on github
