### ISSUE TITLE
[ENHANCEMENT] - Only clean the database when the network connection is present.

### ISSUE THREAD

**Issue by thestraycat** [LibreELEC/LibreELEC.tv#7958]
A mechanism to stop libreelec cleaning all the movies from the database when the network is down and a 'clean' database is performed.

Maybe a toggle box that allows cleaning of the database ONLY when the network is present as a fail safe to blatting the whole database! This would help people with flakey WIFI, and also people that are effected by the RPI 4B WIFI not connecting on startup issues.... especially if a clean is autoperformed at startup or through 3rd party software API calls on tv/movie adding etc.

**Comment by chewitt** [comment]
Closing the ticket because:

a) This is a bug/issue tracker not a feature request tracker (requests go in the forum)
b) The logic for this belongs in Kodi not LE, ergo this would be the wrong project to log the request
c) If you have flakey wifi the solution is fixing the wifi not adding software complexity and workarounds

**Comment by thestraycat** [comment]
Chewitt, 

a) Fair enough but i saw another other [ENHANCEMENT] on the issues page that hadnt been closed so took a punt myself. You might want to close that one as well?

b) Ok.

c) I disagree. With issues around RPI 4B on libreelec forgetting wifi credentials on 1 in 2 reboots for hoardes of people, "fixing the wifi" dosn't seem to be an option specially as each of those threads never resolves in a fix, you yourself have attempted to help people with these issues on the libreelec forums for these very issues. 

This issue has existed for a very long time as well. To conclude, i believe the cleaning operation should at least mention that no network connection is present and do you want to continue as a fail safe. 

It dosn't make any sense to clean the database of 1000's of movies just because there was no active network connection. there's loads of scenarios where this can simply just happen... Say you're playing with your network settings, moving from wifi to lan and get something wrong, have a network outage for some reason, It seems to me that this should be the default behaviour regardless.
