### ISSUE TITLE
System start with TBS device

### ISSUE THREAD

**Issue by jojoxyz** [LibreELEC/LibreELEC.tv#8031]
TBS5520SE - Odroid N2+, CoreElec 

TBS5520SE - Raspberry-Pi-3-Model-B-Rev-1.2 , LibreElec

In both cases, the problem is the same. 

  
When I plug in the power, the system has a problem starting. The system will start booting and a little while before the Kodi screen starts, the system will crash and start restarting. This is repeated 1 to 2 times. After that, the system will start normally. The important thing is that it only happens when connected to the power supply. Restarting using the OSD menu works normally. The worse case is when the system does not crash, but freezes. It is then necessary to remove the power cable and repeat the whole process until it can be started. 

  
I found this problem from Kodi version Lea and Matrix. 

  
I didn't have this problem when I used Armbian or Raspbian + TBS drivers. 

  

Is there any solution for this?

**Comment by heitbaum** [comment]
> TBS5520SE - Odroid N2+, CoreElec
> 
> TBS5520SE - Raspberry-Pi-3-Model-B-Rev-1.2 , LibreElec
> 
> In both cases, the problem is the same.
> 
> When I plug in the power, the system has a problem starting. The system will start booting and a little while before the Kodi screen starts, the system will crash and start restarting. This is repeated 1 to 2 times. After that, the system will start normally. The important thing is that it only happens when connected to the power supply. Restarting using the OSD menu works normally. The worse case is when the system does not crash, but freezes. It is then necessary to remove the power cable and repeat the whole process until it can be started.
> 
> I found this problem from Kodi version Lea and Matrix.
> 
> I didn't have this problem when I used Armbian or Raspbian + TBS drivers.
> 
> Is there any solution for this?

Please use forum for support.
