### ISSUE TITLE
[BUG] Docker update and docker.linuxserver.portainer

### ISSUE THREAD

**Issue by easyfab** [LibreELEC/LibreELEC.tv#8045]
### Describe the bug
With new Docker update, Portainer ( installed from addons ) doesn't launch.

And with docker.linuxserver.portainer command I have this message.

 portainer
http: invalid Host header

### Informations
 - LE Version: 	LibreELEC-RPi4.aarch64-12.0-nightly-20230809-c46fefd.img.gz 
 - Hardware Platform: RPI4

**Comment by easyfab** [comment]
From https://github.com/LibreELEC/LibreELEC.tv/pull/8032 and https://github.com/moby/moby/releases/tag/v24.0.5

I see : 
The Go client now avoids using UNIX socket paths in the HTTP Host: header, in order to be compatible with changes introduced in go1.20.6. https://github.com/moby/moby/pull/45962, https://github.com/moby/moby/pull/45990

Could this be related to the problem ?

**Comment by heitbaum** [comment]
- Fixed in #8032
- Should be available shortly

**Comment by easyfab** [comment]
All good now.

Thank you for your quick reply and for all your great work.
