### ISSUE TITLE
[BUG] Can't boot after "getedid create"

### ISSUE THREAD

**Issue by Marc--** [LibreELEC/LibreELEC.tv#8069]
### Describe the bug
On a fresh LE11 install, my last step was to create edid. I ran "getedid create", then the computer reboots.

I now have an error message 👍 
**Failed to Allocate memory for Kernel command line, bailing out
booting kernel failed: bad file number**

### How to reproduce
1. Install LE11
2. run "getedid create"
3. See error

### Information
 - LibreELEC Version: 11.0.3
 - Hardware Platform: x86 (Asus CN65 Chromebox with MrChromebox UEFI bios)

### Log file
Can't access logs.

### Context
All was fine before, but i need edid to use my setup.

**Comment by Marc--** [comment]
I manage to boot again : 

1. Boot from USB "systemrescue".
2. Mount boot FS
3. Edit syslinux.cfg and remove edid stuff.

Can someone help me, i lack of knowledge to understant why it appens, and i need edid .

**Comment by heitbaum** [comment]
Please use the forum for support
