### ISSUE TITLE
[BUG] Update from LE12 nightly db892cd to c3d17f9 breaks PVR Client

### ISSUE THREAD

**Issue by eldersixpack13** [LibreELEC/LibreELEC.tv#8089]
### Describe the bug
update LE12 nightly db892cd to c3d17f9 breaks PVR Client - TvHeadend HTSP Client

a "grep -i pvr *.log|grep -i compa"
=>
"2023-09-01 02:10:31.248 T:985      info <general>: ADDON: pvr.hts version 21.0.1.2 is **incompatible**"

### How to reproduce
1. update
2. reboot
3. See error (Photo):
![1](https://github.com/LibreELEC/LibreELEC.tv/assets/83478572/c93fc2a2-7f2b-489e-b542-b39c0779fcd6)

### Information
 - LibreELEC Version: LE 12 nightly (c3d17f9)
 - Hardware Platform: NUC13 (ANHi5)

### Log file
[kodi.log](https://github.com/LibreELEC/LibreELEC.tv/files/12491746/kodi.log)

### Context
tried without success:
- remove Addon DB, reboot, activate installed addon's
-  reinstall PVR Client - TVheadend HTSP
output text:
"_Failed to install add-on from zipfile.
The dependency on kodi.binary.instance.inputstream version 3.2.0 could not be satisfied_"

in an other case: the addon wasn't  findable at all via Addon search (_hardcore !!!_)

-  restored a backup (from 29.08.2023; I guess before update to db892cd)

my workaround:
- downgrade to db892cd
-  reboot
- manual copy pvr directories from a backup
-  reboot

**Comment by heitbaum** [comment]
- Fixed by #8092
