### ISSUE TITLE
PULSEAUDIO is missing from the audio output devices list

### ISSUE THREAD

**Issue by smp79** [LibreELEC/LibreELEC.tv#8222]
Reverting https://github.com/xbmc/xbmc/commit/a30bb554690dac6120351cf7a4bc57841600445a fixes it.
Not sure if this needs to be fixed in Kodi or LE build system, so posting it here.

**Comment by HiassofT** [comment]
This seems to be a kodi bug, `-DHAS_PULSEAUDIO=1` got dropped but this is still required to be set for `xbmc/platform/linux/OptionalsReg.cpp`

can you please open a kodi issue?

**Comment by smp79** [comment]
https://github.com/xbmc/xbmc/issues/23952
