### ISSUE TITLE
[BUG] sundtek-media build failing

### ISSUE THREAD

**Issue by heitbaum** [LibreELEC/LibreELEC.tv#8296]
### Describe the bug

sundtek.de/media/latest.phtml download is erroring

### How to reproduce
1. scripts/build sundtek-mediatv

### Information
 - LibreELEC Version: [e.g. 9.2.1] all
 - Hardware Platform: [e.g. RPi3] all

### Log file

```
$ s/build sundtek-mediatv
BUILD      sundtek-mediatv (target)
    TOOLCHAIN      manual
--2023-11-06 12:26:26--  http://sundtek.de/media/netinst/64bit/installer.tar.gz
Resolving sundtek.de (sundtek.de)... 85.10.198.106
Connecting to sundtek.de (sundtek.de)|85.10.198.106|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1737652 (1.7M) [application/octet-stream]
Saving to: 'installer.tar.gz'

installer.tar.gz                 100%[==========================================================>]   1.66M  1.15MB/s    in 1.4s    

2023-11-06 12:26:28 (1.15 MB/s) - 'installer.tar.gz' saved [1737652/1737652]

--2023-11-06 12:26:28--  http://sundtek.de/media/latest.phtml
Resolving sundtek.de (sundtek.de)... 85.10.198.106
Connecting to sundtek.de (sundtek.de)|85.10.198.106|:80... connected.
HTTP request sent, awaiting response... 403 Forbidden
2023-11-06 12:26:28 ERROR 403: Forbidden.

FAILURE: s/build sundtek-mediatv during make_target (package.mk)
*********** FAILED COMMAND ***********
wget -O version.used http://sundtek.de/media/latest.phtml
**************************************
```

**Comment by sundtek** [comment]
The issue can be closed, we upgraded the server. The new PHP configuration wiped out support for files with phtml extension - we just fixed it.
Thank you for reporting!

**Comment by heitbaum** [comment]
> The issue can be closed, we upgraded the server exactly a f. The new PHP configuration wiped out support for files with phtml extension - we just fixed it. Thank you for reporting!
> 
> It is important that this link is valid many scripts out there are using it for checking for updates.

Thanks. Working now.
