### ISSUE TITLE
[BUG] No direct shutdown by IR remote in Libreelec 12

### ISSUE THREAD

**Issue by guenniguenzelsen** [LibreELEC/LibreELEC.tv#8300]
### Describe the bug
Until Libreelec 11 I had two options to shut down the HTPC with my IR remote.
1. Navigate to the exit menu and chose shutdown, restart, etc
2. Press on/off button on my IR remote to directly shut down.

Now with Libreelec 12, option 2 seems to be disappeared and by pressing on/off button on my IR remote the exit menu pops up.

Usecase:
- Whatching a movie in Kodi first
- Later switch from HTPC to standard TV to watch some stuff/news (HDMI-1 to AV)
- When it comes to turning off all devices it's just one (blind) click on the on/off button on the Kodi IR-remote and the HTPC will shut down without the need of blind operating a context-menu 

### How to reproduce
2. Play '....'
3. See error

### Information
 - LibreELEC Version: [e.g. 9.2.1]
 - Hardware Platform: [e.g. RPi3]

**Comment by HiassofT** [comment]
This is an intentional change, see https://github.com/xbmc/xbmc/pull/23806

If you want kodi to immediately shutdown you can configure that via a keymap (eg by using the Keymap Editor addon) https://kodi.wiki/view/Keymap
