### ISSUE TITLE
[BUG] Flickering and Colorpumping with Netflix plugin. Creator says external problem

### ISSUE THREAD

**Issue by DDQW** [LibreELEC/LibreELEC.tv#8323]
### Describe the bug
Flickering and color"pumping" (changes between saturated and unsaturated colors) while using the netflix plugin. creator of plugin says it is an external (kodi or elec) problem even though it only happens with the netflix plugin
https://github.com/CastagnaIT/plugin.video.netflix/issues/1644
### How to reproduce
open netflix plugin
play something

### Information
latest 20 alpha but it also happend with stable of 19 and 20

### Log file
https://paste.kodi.tv/nufefeduqi.kodi

**Comment by heitbaum** [comment]
Is this issue still occurring with latest LE12 20240311-86dba4b images. If so please share the updated debug logs. Alternatively please raise this on the forum for support.

**Comment by heitbaum** [comment]
Closing as inactive. Happy to open again - but will need debug logs, ideally a reproducible case. Using the forum for support may get more answers as others may have seen the same issue.

**Comment by DDQW** [comment]
Sadly still not working. I have an account on the libreelec board for a while now but for some reason i have no option to post. 
If you are an admin there please contact me over private message i don't want to post my account name here :D

**Comment by heitbaum** [comment]
> Sadly still not working. I have an account on the libreelec board for a while now but for some reason i have no option to post. If you are an admin there please contact me over private message i don't want to post my account name here :D

@chewitt / @CvH can you help?

**Comment by CvH** [comment]
@DDQW whats your forum name ?

**Comment by DDQW** [comment]
https://forum.libreelec.tv/core/user/31924-mordred/

**Comment by CvH** [comment]
@DDQW please try again, should work now

**Comment by DDQW** [comment]
sadly also no. i have subscribe, mark all as read and rssfeed as options. No way to create or answer anywhere (currently i am in general support)

i did log out and relogin and a cache reset with strg+f5

**Comment by CvH** [comment]
@DDQW pls try again, if this is not working I can remove the account and you can reregister - its unclear why you can't do anything at the forum (we had this before at other accounts).

**Comment by DDQW** [comment]
still no feel free to nuke it and thx for the sup

**Comment by CvH** [comment]
@DDQW done

**Comment by DDQW** [comment]
i tried again a few days ago same mail still not able to post anything. do you maybe work with a tld whitelist so it refuses to accept my personal domain?

**Comment by CvH** [comment]
can you drop me a mail at myname (c...) @libreelec.tv ?
I am not too sure what happen but we can fix this.

**Comment by DDQW** [comment]
the mail is out. it might have gone to spam you might want to check it.

**Comment by DDQW** [comment]
https://forum.libreelec.tv/thread/29577-x86-64-netflix-colorpumping-and-flickering/

in case someone stubmbles over this it now is in the libreelec forum
