### ISSUE TITLE
[BUG] "unsupported compression type 4" with Amlogic u-boot on certain hardware

### ISSUE THREAD

**Issue by ballerburg9005** [LibreELEC/LibreELEC.tv#8357]
### Describe the bug
On some hardware, using latest u-boot blobs (~2023), the kernel cannot load because it is compressed with an "unsupported compression type 4". I asked the supplier of the blobs (https://github.com/ophub/u-boot) if this can be fixed, with the sad response "Amlogic is not open source".

**However, there is an obvious easy solution that comes at no cost:** simply supply the uncompressed kernel files alongside LibreELEC.

### How to reproduce
1. Have a particular oddball Amlogic box
2. Have no choice but to use the latest u-boot binary from Amlogic
3. Upon kernel load in serial console, the message appears "unsupported compression type 4"
_4. Install Armbian with Linux 6 instead, which works, solely for the reason of not using kernel image compression_

### Information
905d Mecool Ki Pro with updated [u-boot-p212.bin](https://github.com/ophub/u-boot/tree/main/u-boot/amlogic/overload) (it is from 2021 or 2023 or so)
LibreELEC 11.0

**Comment by heitbaum** [comment]
Ref: 
- https://github.com/ophub/u-boot/issues/9

not planned to address
