### ISSUE TITLE
[BUG] OSD not rendered correctly

### ISSUE THREAD

**Issue by drk1900** [LibreELEC/LibreELEC.tv#8461]
### Describe the bug
"reloaded" mode in Artic Zhephyr OSD not rendered correctly

### How to reproduce
1. Open any movie or music file and change OSD mode to "reloaded"

### Information
 - LibreELEC-RPi4.aarch64-12.0-nightly-20231229-4e24516
 - Hardware Platform: [RPi4]

### Context
Not happening in build LibreELEC-RPi4.aarch64-12.0-nightly-20231213 or before

**Comment by CvH** [comment]
can you check what version is the first one that fails ?
So does [20231224](https://test.libreelec.tv/12.0/RPi/RPi4/LibreELEC-RPi4.aarch64-12.0-nightly-20231224-8fece3c.img.gz) and [20231227](https://test.libreelec.tv/12.0/RPi/RPi4/LibreELEC-RPi4.aarch64-12.0-nightly-20231227-74ff04a.img.gz) also shows that problem ?

https://github.com/LibreELEC/LibreELEC.tv/compare/581a2fe...4e24516

**Comment by drk1900** [comment]
Yes, same issue in any build including 20231229

**Comment by drk1900** [comment]
![IMG_20231229_123716](https://github.com/LibreELEC/LibreELEC.tv/assets/155182937/be391c29-1838-4394-b80e-91aa02624339)

**Comment by drk1900** [comment]
It looks like this, instead of the transparency gradient in 20231223 or previous

**Comment by drk1900** [comment]
231213 is the last that works OK

**Comment by CvH** [comment]
https://github.com/LibreELEC/LibreELEC.tv/compare/a1a3979...63347fc

likewise due a RPi kernel bump
can you share a complete logfile from 231213 and 231216

**Comment by drk1900** [comment]
https://paste.libreelec.tv/harmless-jackass.log

**Comment by drk1900** [comment]
https://paste.libreelec.tv/mint-goat.log

**Comment by heitbaum** [comment]
- is this related to #8488

**Comment by neo1973** [comment]
> is this related to https://github.com/LibreELEC/LibreELEC.tv/issues/8488

Probably not, RPi4 doesn't support fences:

```
warning <general>: [GBM] missing support for EGL_KHR_fence_sync and EGL_ANDROID_native_fence_sync - performance may be impacted
```

**Comment by drk1900** [comment]
After a try with today build, 240109, no luck again, even with kernel 6.6.10, but changing the video player render method to EGL solves the issue

**Comment by nekromantik** [comment]
I am seeing same on RPi5
Only on the OSD when playing movie

**Comment by HiassofT** [comment]
Yes, that's a known issue and we are still thinking about how to best solve it.

Kodi prefers to use 30bit planes (10bit per R/G/B channel) so that leaves only 2 bits for alpha channel and thus the transparency looks crap.
