### ISSUE TITLE
[BUG] LibreELEC-RPi5.arm-11.0.4.img.gz having problems install unknown repos with Raspberry pi 5

### ISSUE THREAD

**Issue by mrusli70** [LibreELEC/LibreELEC.tv#8486]
### How to reproduce
2. Play '....'
3. See error

### Information
 - LibreELEC Version: 11.0.4
 - Hardware Platform: Rpi5 (raspberry pi 5)

### Log file
cannot produce at this moment

### Context
I could not install unknown repos with my raspberry pi 5 with libreelec version 11.0.4. There seems to be software bugs with raspberry pi 5 that it can't seems to install. 

But i did not have any problems with version 11.0.4 with raspberry pi 4. 

I have test over and over again but still it cannot install any unknown repos with raspberry pi 5

**Comment by chewitt** [comment]
Please use the forums for support (and start with a Kodi debug log): https://forum.libreelec.tv
