### ISSUE TITLE
[BUG] nfs mount support dropped with #8497

### ISSUE THREAD

**Issue by misanthropos** [LibreELEC/LibreELEC.tv#8511]
### Describe the bug
there is no nfs mount support in util-linux 

### How to reproduce
LE lost nfs mount support with #8497 

### Information
 - LibreELEC Version: master
 - Hardware Platform: RPi4

### Context
This could be solved by adding nfs-utils

**Comment by chewitt** [comment]
Should be fixed with https://github.com/LibreELEC/LibreELEC.tv/pull/8509

**Comment by misanthropos** [comment]
fixed with 09fa08748cfe46cec49d329fb4710c0347bb5a19
even mount on system startup works as before via systemd service
