### ISSUE TITLE
[BUG] ModuleNotFoundError: No module named 'PIL.Image'

### ISSUE THREAD

**Issue by henri-funck** [LibreELEC/LibreELEC.tv#8534]
### Describe the bug
Librespot is unable to import PIL.Image

### How to reproduce
Librespot installed on LibreELEC nightly-20240119-71b413e (RPi5.aarch64)

### Information
 - LibreELEC Version: nightly-20240119-71b413e
 - Hardware Platform:  RPi5.aarch64

### Log file
```
EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'ModuleNotFoundError'>
                                                   Error Contents: No module named 'PIL.Image'
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/service.librespot/default.py", line 24, in <module>
                                                       import service
                                                     File "/storage/.kodi/addons/service.librespot/resources/lib/service.py", line 1, in <module>
                                                       import PIL.Image
                                                   ModuleNotFoundError: No module named 'PIL.Image'
                                                   -->End of Python script error report<--
```

### Context
This might have something to do with commit #8527 that updates Pillow.

Hi,
I tried to install Librespot on a current nightly, but the addon fails at the first line.
I would gladly submit a pull request to fix this, but I do not know how to import PIL.
Another option would be to use the unformatted fanarts, but they look awful in Kodi.
Thanks for advice.

**Comment by heitbaum** [comment]
I have raised an issue with Pillow. I can’t spot the change in the setup.py that has caused this.
