### ISSUE TITLE
Logitech mouse and keyboard stop working overnight[BUG]

### ISSUE THREAD

**Issue by arcasys** [LibreELEC/LibreELEC.tv#8566]
### Describe the bug
After a certain period of time both mouse and keyboard stop working.
Mouse Logitech M310 and keyboard K330 are paired with a Logitech Unifying receiver.
Detaching and reattaching the receiver does not help.
After a reboot everything is back to normal.

### How to reproduce
1. dmesg (after reboot)
3. Play '....'

### Information
 - LibreELEC Version: 11.0.5
 - Hardware Platform: RPi3+

**Comment by chewitt** [comment]
Please open a thread in the forum. This is a bug tracker not a support channel. Thanks.
