### ISSUE TITLE
[BUG] Tanix TX6 LAN doesnt work properly on all LE12 Nightly builds after 2023.04.27

### ISSUE THREAD

**Issue by PinkyAcorn** [LibreELEC/LibreELEC.tv#8615]
### Describe the bug
LAN connection broken on Tanix TX6 on LE12 Nightly builds after 2023.04.27 (tested up to 2024.02.12)
DHCP assigns wrong ip (169.254.xxx.xxx / 16)
Manual IP connection does not work either

### How to reproduce
Connect to internet over LAN

### Information
 - LibreELEC Version: LibreELEC-H6.aarch64-12.0-nightly-20230428-14e548e-tanix-tx6.img.gz
 - Hardware Platform: Tanix TX6 

### Context
LAN stopped working after Linux kernel upgrade from 6.1 to 6.3
(2023.04.27 build uses 6.1 kernel, 2023.04.28 uses 6.3 kernel)
https://github.com/LibreELEC/LibreELEC.tv/pull/7586

**Comment by heitbaum** [comment]
Please use the forum https://forum.libreelec.tv/  for support and provide debug logs. For the tx6 which model do you have? The most recent testing I did with kernel 6.6.2-rc1 was successful.

**Comment by PinkyAcorn** [comment]
I have a TANIX TX6-H board (CS_H6_TX28_V2.7 20200616.L6)

![back](https://github.com/LibreELEC/LibreELEC.tv/assets/78303212/3ac9c1c4-4337-45ec-b869-31c0cfc08009)
![front](https://github.com/LibreELEC/LibreELEC.tv/assets/78303212/5371ba4f-6707-4643-a667-7d6378c40cf1)

**Comment by PinkyAcorn** [comment]
Logfiles (system.journal + kodi.log + uart bootlog) for both builds

[nightly-20230427-d287ee2 logs.zip](https://github.com/LibreELEC/LibreELEC.tv/files/14275388/nightly-20230427-d287ee2.logs.zip)
[nightly-20230428-14e548e logs.zip](https://github.com/LibreELEC/LibreELEC.tv/files/14275389/nightly-20230428-14e548e.logs.zip)

**Comment by PinkyAcorn** [comment]
Forum post

https://forum.libreelec.tv/thread/28174-bug-tanix-tx6-lan-doesnt-work-properly-on-all-le12-nightly-builds-after-2023-04/
