### ISSUE TITLE
[BUG] AX88179-based USB3.0 to wired Ethernet adapter -- driver does not load on Rpi

### ISSUE THREAD

**Issue by rkershenbaum** [LibreELEC/LibreELEC.tv#8649]
### Describe the bug
LilbreELEC does not load the driver for an AXOS AX88179 chipset USB3.0 to wired Ethernet adapter.

The output from lsusb shows:

`Bus 002 Device 004: ID 0b95:1790 ASIX Electronics Corp. AX88179 Gigabit Ethernet`

### How to reproduce
1. Plug an AX88179-based Ethernet adapter into a USB3.0 port.
2. Check LE settings page / Connections.  
3. eth1 interface will not be present.
4. Enter ifconfig in command line
5. eth1 interface will not be present.

### Information
 - LibreELEC Version: 11.0.6, and LE12 nightly builds (same behavior)
 - Hardware Platform: Rpi5, Rpi4

### Log file

[https://paste.libreelec.tv/square-gobbler.log](url)

### Context

See the discussion here for more information:

[https://forum.libreelec.tv/thread/28119-usb3-to-gigabit-ethernet-adapter-on-rpi4-5-troubles/?pageNo=1](url)

**Comment by chewitt** [comment]
I'm closing this ticket down as the `ax88179_178a` adaptor I have is working with the latest RPi Linux 6.6.y kernel that we have in LE12 and master. There have been fixes added to Linux 6.9/6.10 which are cc'd/backported to stable:

```
RPi5:~ # dmesg | grep ax88179
[    4.443489] ax88179_178a 4-1:1.0 (unnamed net_device) (uninitialized): Failed to read reg index 0x0040: -32
[    4.771937] ax88179_178a 4-1:1.0 eth1: register 'ax88179_178a' at usb-xhci-hcd.1-1, ASIX AX88179 USB 3.0 Gigabit Ethernet, 20:7b:d2:94:c1:e4
[    4.859643] usbcore: registered new interface driver ax88179_178a
[    7.447149] ax88179_178a 4-1:1.0 eth1: ax88179 - Link status is: 1
RPi5:~ # ifconfig
...
eth1      Link encap:Ethernet  HWaddr 20:7B:E2:94:D1:C4  
          inet addr:192.168.100.9  Bcast:172.16.20.255  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:45674 errors:0 dropped:146 overruns:0 frame:0
          TX packets:16717 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:57101630 (54.4 MiB)  TX bytes:1837521 (1.7 MiB)
...
```
