### ISSUE TITLE
[BUG] Boot scrips for AmLogic do not work for some configurations

### ISSUE THREAD

**Issue by iamiub** [LibreELEC/LibreELEC.tv#8716]
I tried installing LibreELEC on a device that was and is running CoreELEC from USB. The reason for doing so was to see if there were eMMC drives in LibreELEC so that the eMMc could be erased before the device is given away (as opposed to going to land fill).

After asking for support on the forum:  https://forum.libreelec.tv/thread/28285-aml-boot-sequence/ I decided to copy of the kernel, system and dtb images for the device onto a CoreELEC install. (ie. CoreELEC script boot script will call kernel with CoreELEC partition for /flash as opposed to LIBREELEC - that is to say the boot arguments were as per CoreELEC).

Amazingly the device booted up with LibreELEC with kodi configured with all the plugins working and the CEC device was working too. 

I can only deduce that the boot scripts didn't like my configuration. As the external hard disk (USB) was disconnected the only difference I can assume is the eMMC state. 

LibreELEC Version: 11.0.6
Hardware Platform:  meson-gxl-s905d-mecool-m8s-plus.dtb

**Comment by chewitt** [comment]
LE intentionally uses a common boot flow and filenaming on ARM SoC boards (except for RPi) and this is not aligned to what CE uses with their releases so you MUST invoke the recovery boot process so vendor u-boot searches for and finds/stores LE bootscripts for use. If you don't do that, vendor u-boot continues to follow CE bootscripts and our default image will not boot (as you experienced). Not a bug..
