### ISSUE TITLE
[BUG] LE12 Beta1: missing custom firewall/iptables settings

### ISSUE THREAD

**Issue by fredrik-eriksson** [LibreELEC/LibreELEC.tv#8736]
### Describe the bug
Firewall setting in LE12 Beta1 lists three options: "Off", "Home" and "Public". Notably the "Custom" firewall setting (still referenced in the help text for this setting) is missing. 

### How to reproduce
1. Go to Settings -> LibreELEC -> Network -> Firewall
2. Try to find the "Custom" firewall setting

### Information
 - LibreELEC Version: 12 Beta1
 - Hardware Platform: RPi5

### Log file
None

### Context
This is a fresh installation.

**Comment by heitbaum** [comment]
Hi @fredrik-eriksson 

I believe you are looking for this:
`NF_CUSTOM_PATH = "/storage/.config/iptables/"`
https://github.com/LibreELEC/service.libreelec.settings/blob/3d3773271cd762f159caf1d12cea65b79763c07a/resources/lib/modules/connman.py#L592-L610

`custom` will be available when the custome rules.v4 is in the directory.

**Comment by heitbaum** [comment]
Closing as not bug. Forum is the best for support.

**Comment by fredrik-eriksson** [comment]
Sorry for the noise, turned out to be a corrupted file system that had emptied everything under .config. Thanks for the pointer!
