### ISSUE TITLE
[BUG] backdoor in xz (in LE too ?)

### ISSUE THREAD

**Issue by eldersixpack13** [LibreELEC/LibreELEC.tv#8772]
### Describe the bug

further reading:
https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/IJRW6X34BBJQLAQ64G53S7XPRU35U7KN/
and
https://github.com/LibreELEC/LibreELEC.tv/pull/8714

**Comment by antonlacon** [comment]
My understanding of https://www.openwall.com/lists/oss-security/2024/03/29/9 is that the malicious code is specifically targeting debian & rpm based distributions. However, the analysis is incomplete and we've pushed a downgrade of the package to hopefully head off the issue entirely.
