### ISSUE TITLE
[BUG] Build on arm64 host (debian bookworm) fails in checkdeps

### ISSUE THREAD

**Issue by rellla** [LibreELEC/LibreELEC.tv#8813]
### Describe the bug
LibreELEC does not build with Debian bookworm on arm64 (RPi5) as host

### How to reproduce
Setup Raspberry Pi OS on a Raspberry PI 5 and simply try to build LE.

### Context
I tried to build LE on a RPi5 with Raspberry Pi OS (Debian bookworm). 
checkdeps fails, because on Debian bookworm, the package for libc.so.6 and ld-linux-x86-64.so.2 is libc6-amd64-cross instead of libc6:amd64 and the files are located in /usr/x86_64-linux-gnu/lib/.

I know, it is not intended, to support all various build hosts and i don't know if this is a wide-range and not only an arm64/bookworm problem. I just wanted to pop up with it, to let you decide if there could be an improvement ;)

Here is the ugly hack, which solves that for my scenario. Though this is not the patch that should go upstream ;)

```
diff --git a/scripts/checkdeps b/scripts/checkdeps
index 34cccdab11..13d29c3aef 100755
--- a/scripts/checkdeps
+++ b/scripts/checkdeps
@@ -101,8 +101,8 @@ if [ "$(uname -m)" = "aarch64" ] && [ "${PROJECT}" = "Rockchip" -o "${PROJECT}"
   if [ ! -f /lib64/ld-linux-x86-64.so.2 -o ! -f /lib/x86_64-linux-gnu/libc.so.6 ]; then
     echo -e "Copy from a working x86_64 system:\n\t/lib64/ld-linux-x86-64.so.2\n\t/lib/x86_64-linux-gnu/libc.so.6"
   fi
-  file_map[/lib64/ld-linux-x86-64.so.2]="libc6:amd64"
-  file_map[/lib/x86_64-linux-gnu/libc.so.6]="libc6:amd64"
+  file_map[/usr/x86_64-linux-gnu/lib/ld-linux-x86-64.so.2]="libc6-amd64-cross"
+  file_map[/usr/x86_64-linux-gnu/lib/libc.so.6]="libc6-amd64-cross"
 fi

 # remap or add [depend]=package needs based on host distro
```

**Comment by antonlacon** [comment]
If memory serves, the file locations and package names for this were pulled from an x86-64 VM some years ago. Please open a PR with the change above. Debian/Ubuntu are the expected default distros for checkdeps and the file locations are the same: https://packages.ubuntu.com/jammy/all/libc6-amd64-cross/filelist

Please delete the if test above noting to copy from a working x86-64 system while at it.
