### ISSUE TITLE
[BUG] audio not initialised on Generic-Legacy (x86_64) with nvdia card after boot/restart

### ISSUE THREAD

**Issue by VanillaFord** [LibreELEC/LibreELEC.tv#8906]
### Describe the bug
This bug has been present with LE 12.0 as well as 11.0.6
Running on an older intel platform with iG630 and nvidia  GT-430 using connection via HDMI via an Pulseeight CEC adapter to the TV
After booting up, the kodi UI shows fine, however audio is not present, either while playing a video nor clicking sounds from menu.
Going to audio settings and changing driver to pulse audio and back to nvidia resolves the issue and audio is playing fine after that (without a reboot).
After a reboot/fresh start,, the problem is back.
hence my feeling is, that the problem lies somewhere in the first initialisation of the driver after boot.

### How to reproduce
1. install LE 12.0 or 11.0.6 (generic-legacy)
2.  after Kodi UI shoes, CEC is working fine but no Audio.
3. under Settings, the NVIDIA Card and HDMI Output to TV is selected correctly, however there is no sound (either from playing video or from menu clicks).
4.  switching audio driver to pulse-audio and then back to nvidia resolves the problem and audio is playing fine.
5. after a reboot the problem is back

### Information
 - LibreELEC Version: 12.0 and 11.0.6
 - Hardware Platform: i630 with nvidia gt-430
 - additional hardware: pulseeight CEC adapter

**Comment by heitbaum** [comment]
Please use forum for support and share the debug logs. Good to have the background of that it didn’t work with LE11 either, but all investigation should be done on LE12/13. LE11 is not receiving any further development.
