### ISSUE TITLE
[BUG] Some interlaced videos are not de-interlaced on Raspberry Pi 4

### ISSUE THREAD

**Issue by cjee21** [LibreELEC/LibreELEC.tv#8960]
### Describe the bug
Firstly, thank you for the software de-interlacer which enabled most of my interlaced videos to play smoothly unlike before. However, a few interlaced videos are still not de-interlaced.

### How to reproduce
1. Play the attached sample video on LibreELEC Raspberry Pi 4.
2. Press `O` on keyboard to check de-interlacing.

### Information
 - LibreELEC Version: 12.0.0, 12.0.1
 - Hardware Platform: Raspberry Pi 4

### Sample video
[test.zip](https://github.com/user-attachments/files/15567371/test.zip)

### Context
The sample video (test.mkv) is cropped with FFmpeg from a full-length mkv extracted from a genuine legally owned Blu-ray Disc without re-encoding. The video is detected as interlaced by both MediaInfo and FFmpeg. When played on a Windows PC with both Kodi and MPC-BE, it is correctly identified as interlaced and played back properly. For some reason, LibreELEC on Raspberry Pi 4 is playing it back as a progressive video. This happens on a few interlaced videos extracted from a few genuine Blu-rays. Other interlaced videos that are also from genuine Blu-rays play back fine with software de-interlacing.

![01](https://github.com/LibreELEC/LibreELEC.tv/assets/77721854/74a4f725-b447-4e9d-ac73-821b71a174d4)

**Comment by cjee21** [comment]
Tested on LibreELEC 12.0.1. This issue is still reproducible.

**Comment by HiassofT** [comment]
Thanks for the report!

I just talked with the RPi engineers and this is a known issue in the H264 hardware video decoder, it sometimes doesn't detect interlaced videos correctly. It's a bit of a tricky issue and so far there's no ETA if/when this will be fixed.

As a workaround you can (temporarily) disable HW video decoding (Settings->Player->Videos->Allow hardware acceleration with DRM PRIME), then the video will be software-decoded (RPi4 should handle this fine) and deinterlacing works

**Comment by popcornmix** [comment]
I have a [test firmware](https://drive.google.com/file/d/1FLUU7bF7TeoqTm9cGzCsPShLa3KOpRr_/view?usp=drivesdk) that you could try.

Replace start.elf/fixup.dat on the LibreELEC boot partition with start4x.elf and fixup4x.dat from the zip file.
(take a copy of original start.elf/fixup.dat in case you want to go back).

Then test some interlaced/progressive files and see if interlace seems to be enabled correctly.

**Comment by popcornmix** [comment]
Thanks for testing - it's been pushed to rpi-update firmware, so should be picked up in LibreELEC builds in due course.
