### ISSUE TITLE
[BUG] CEC configuration broken

### ISSUE THREAD

**Issue by damnms** [LibreELEC/LibreELEC.tv#9002]
### Describe the bug

I installed LE nightly to a SD for a rpi5. I noticed that the rpi5 ignores power off/power on from the TV. So i checked the settings and noticed that i have 2 CEC adapter settings. When i configured one, the other had the same configuration. After a reboot, they were like resetted.

### How to reproduce
1. Go to cec adapter settings
2. configure the first one to use e.g. hdmi port 1
3. configure the other to use e.g. hdmi port 2
4. check the first one, it will be hdmi port 2
5. do a reboot
6. check again the settings, all is back like resetted

### Information
 - LibreELEC Version: nightly
 - Hardware Platform: rpi5

**Comment by heitbaum** [comment]
- Closing now that #9254 and #9255 are merged in nightlies. If still an issue please raise on the forum/a bug can be raised.
