### ISSUE TITLE
Only basic PS3 Remote buttons work in LibreElec 12

### ISSUE THREAD

**Issue by thegrandpoobah** [LibreELEC/LibreELEC.tv#9009]
### Describe the bug
In LibreElec 10, most of the buttons on the PS3 Remote (which has a huge compliment of buttons) were mapped to different functions in the UI. Prominently, "Top Menu" brought up the context menu, the number pad would bring different letters into focus on long list (i.e. press 2 and it would go A, then B, then C, a la a phone dial pad) and pause would actually pause the video. Very convenient.

In LibreElec 12, only the most basic buttons work, navigation, enter and a couple others. Workable, but less convenient :)
 
See also here for others experiencing the issue: https://forum.libreelec.tv/thread/28568-libreelec-12-mapping-ps3-bd-remote-buttons/

### How to reproduce
1. Pair a PS3 Remote Control
2. Press the Pause Button on the Remote
3. Nothing happens

### Information
 - LibreELec 12.0
 - RPi4
 - No keymapping plugins in Kodi, this is "out of the box" experience for both LibreElec 12 and LibreElec 10.

**Comment by heitbaum** [comment]
Best raise this on the forum for support. If you has a proposed fix then please raise a PR for review.
