### ISSUE TITLE
PS3 Remote Battery Drain on LibreElec 12

### ISSUE THREAD

**Issue by thegrandpoobah** [LibreELEC/LibreELEC.tv#9010]
### Describe the bug
The PS3 Remote is a pretty power hungry, so its typically put into a low power mode after a couple minutes of inactivity. In this mode, the first press on the PS3 Remote would wake up the control and then a couple seconds later, subsequent presses would be handled by Kodi. Battery would last a very long time in this mode.

In LibreElec 10, this was handled correctly in the out of the box experience, but in LibreElec 12 the remote is constantly in its "on" mode, thereby reducing the battery life significantly (on the matter of days) 

### How to reproduce
1. Pair your PS3 Remote
2. Use Kodi as you would
3. Battery runs out after a couple days

In practice it should be:
1. Pair your PS3 Remote
2. Use Kodi as you would
3. WHen not in use, the remote goes into power save mode
4. Press button on Remote, wait for remote to re-pair, continue using Kodi.

### Information
 - LibreELEC 12.0 (Straight out of the box experience, no input addons)
 - RPi4
 - PS3 Remote (First Gen, not the one with the IR Blaster)

**Comment by heitbaum** [comment]
Best raise this on the forum for support.
