### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by imboii** [LibreELEC/LibreELEC.tv#9032]
### Describe the bug
Adult swim keep's giving a error
### How to reproduce
1. Go to install from repository
2. Press on all repositories 
3. Press video add-ons
4. Install Adult Swim
5. Start up Adult swim and get a error 

### Information
 - LibreELEC Version: 12.0.0
 - Hardware Platform: rpi 4

### Log file
Can't it says error uploading log files please try agian over and over

### Context
It doesn't work even if it's the first addon i install

**Comment by chewitt** [comment]
This is development bug tracker. The forum is here: https://forum.libreelec.tv
