### ISSUE TITLE
[BUG] Cannot boot Odroid N2+ with 12.0.0 image, official release version or nightly built version

### ISSUE THREAD

**Issue by mood-indigo** [LibreELEC/LibreELEC.tv#9104]
The image is not "corrupted" but the file path to the dtb files is incorrect. The fix was merged in https://github.com/LibreELEC/LibreELEC.tv/pull/9030 two weeks ago.

Use a current nightly image from https://test.libreelec.tv/12.0/Amlogic/odroid-n2/ .. beware the folder contains old arm images too. You need the latest aarch64 one. Or you can install using LE11 then update to LE12.

_Originally posted by @chewitt in https://github.com/LibreELEC/LibreELEC.tv/issues/9099#issuecomment-2232473687_
            
I have downloaded all the 12.0.0 images on https://libreelec.tv/downloads/amlogic/ to compare them. They differ only in the `extlinux/extlinux.conf` file; in particularly the difference is only in the value of the `FDT` field (except the Odroid-C4 and Odroid-N2 images do not have this field but the `FDTDIR` field). For example, the `FDT` value for the NanoPi image is `/amlogic/meson-gxbb-nanopi-k2.dtb` while the value in the WeTek Play2 image is `/amlogic/meson-gxbb-wetek-play2.dtb`.

I now suspect the bug is in the script that builds the images; this script does not build a working image for the Odroid N2+ device.

The abovementioned [#9030](https://github.com/LibreELEC/LibreELEC.tv/pull/9030) contains the "remove-amlogic-prefix" patch for the Odroid N2+.  So, maybe the build script should lay the odroid-*.dbt file in the topdir instead of the `amlogic` directory, unlike the images for the other amlogic devices.  I am just guessing here.

**Comment by heitbaum** [comment]
Is this still happening in LE13 nightlies?

**Comment by heitbaum** [comment]
If still an issue. Please raise on the forums.
