### ISSUE TITLE
[BUG] No sound out of the 3.5mm jack on Pi 3

### ISSUE THREAD

**Issue by JonnyGators** [LibreELEC/LibreELEC.tv#9181]
### Describe the bug

When playing back music, there is no sound output the 3.5 mm jack on a Raspberry Pi 3

### How to reproduce
Setup on Pi 3
Try to play music
Hear the silence

### Information
 - LibreELEC Version: 12.0.0
 - Hardware Platform: Raspberry Pi 3

**Comment by chewitt** [comment]
The support forum is here: https://forum.libreelec.tv

**Comment by JonnyGators** [comment]
The complete lack of audio output working for an app that is designed to output audio is a glaring bug, and puzzling choice.  Even more puzzling is closing out such a glaring bug with no explanation.

I've yet to encounter a more stupid scenario than an audio player that is designed to not output audio.

**Comment by chewitt** [comment]
It's a config issue requiring a one-line change not a bug.
