### ISSUE TITLE
[BUG] Hang on boot if MySQL and no network - workaround (no fix in kodi yet)

### ISSUE THREAD

**Issue by egabosh** [LibreELEC/LibreELEC.tv#9215]
Moin,

if MySQL is configured in Kodi, LibreELEC or Kodi will not boot if there is no network. This is problematic because the network for the LibreELEC box is configured within Kodi.
If, for example, the WLAN access data has changed and you want to use your LibreELEC Raspi at a different location and have to configure the network there so that the database is reached, this is not possible in the usual way, but in the best case only cumbersome.

Wouldn't it be possible to do a DB test before starting Kodi if MySQL is configured. If this is not successful after e.g. 2 minutes of trying, a fallback to the local sqlite dbs would be useful, e.g. by temporary automatic adjustment of the config.

An issue with Kodi has existed since 2022, but unfortunately it does not seem to be fixed. 
https://github.com/xbmc/xbmc/issues/21945
Hence the idea of this workaround on the part of LibreELEC.

### Information
 - LibreELEC Version: 12
 - Hardware Platform: RPi4

**Comment by heitbaum** [comment]
@egabosh something for Kodi? Or if it was for LE (I don’t necessarily think it is a general purpose enhancement) the a PR would be the better approach. 

The forum is also a much better place to discuss enhancements/etc. e.g. there may be some systemd / autostart.sh that you could do to achieve what you are trying.
