### ISSUE TITLE
[BUG] Raspberry Pi 5 2gb not rendering LibreELEC 12.0 

### ISSUE THREAD

**Issue by stalko** [LibreELEC/LibreELEC.tv#9243]
### Describe the bug
After installing fresh LibreELEC 12.0 and waiting for resizing a volume the interface seems to be not fully loaded. Look at the picture below:
![IMG_4464](https://github.com/user-attachments/assets/dfd5ea8f-e852-42cd-a0c1-8c6d59e774dd)

With the keyboard I can navigate somewhere, by guessing how the interface will look like. But there was no chance to connect this thing to the network for debugging.

### How to reproduce
1. Flashing microSD card with Raspberry Pi Imager(on mac) or LibreELEC USB-SD Creator(on Windows).
2. Plugging pi 5 to external monitor(with HDMI0), placing microSD card and power cable.
3. Waiting to finish resizing a volume with automatic rebooting after 15 secs.
4. See not fully rendered screen. But still can interact with it by hitting random buttons on keyboard.

### Information
 - LibreELEC Version: 12.0
 - Hardware Platform: RPi5 2GB

### Context
I've tried to install Full Raspbian OS - it works fine.
The eeprom firmware was updated to the latest version.

**Comment by heitbaum** [comment]
The support forum is here: https://forum.libreelec.tv
