### ISSUE TITLE
[BUG] Hauppauge WinTV Nova DVB-S2 USB Tuner not recognized

### ISSUE THREAD

**Issue by harmlessdrudge** [LibreELEC/LibreELEC.tv#9325]
### Describe the bug

Hauppauge WinTV Nova DVB-S2 USB Tuner not recognized
### How to reproduce
Install LibreElec and TVHeadend and try to configure tuner; it's not detected.
### Information
LibreElec 12.0.1 on Lenovo M920q with 8Gb RAM with Hauppauge WinTV NOVA DVB-S2 USB tuner with TVHeadend 4.3

### Log file

https://paste.libreelec.tv/correct-shark.log

### Context

I previously tried with a Raspberry Pi3 with the same result, also with TVHeadend 4.2. This is a popular tuner. I've been using a PCI version of this tuner for many years in a desktop (currently w LibreElec) for a dozen years without issue but want to move to a smaller box. I realize it may be a kernel issue; has been reported before and is apparently unresolved, or was resolved and there's been a regression

[ttps://forum.libreelec.tv/thread/23279-haupage-wintv-nova-hd-usb2-not-recognize-in-tvheadend/](https://forum.libreelec.tv/thread/23279-haupage-wintv-nova-hd-usb2-not-recognize-in-tvheadend/)

**Comment by heitbaum** [comment]
Please use forum for support - search for Hauppauge. The forum post from 2021 is probably outdated.

the em28xx driver is included and seems to match the product. 
https://linuxtv.org/wiki/index.php/Em28xx_devices
https://www.linuxquestions.org/questions/linux-hardware-18/unable-to-get-hauppauge-wintv-dualhd-tuner-working-on-el9-4175719871/

I can’t see the USB device in the logs shared.

start with lsusb and check the dregs logs when inserted.

see you on the forum.
