### ISSUE TITLE
[BUG] Orange Pi PC won't boot.  Has been broken for a while

### ISSUE THREAD

**Issue by NickelNuts** [LibreELEC/LibreELEC.tv#9337]
This has been discussed in the forum here:  https://forum.libreelec.tv/thread/28364-compiling-from-master-doesn-t-generate-bootable-orange-pi-pc-images-any-more/?postID=190326&highlight=orange%2Bpi%2Bpc#post190326

I created this post here because it looks like the post from August 14, 2024, describes a simple fix to the u-boot patches.

Sorry, my technical skills are not great, but I do have a Orange PI PC I could test an image on

I was able to get version LibreELEC-H3.arm-13.0-nightly-20240929-8602b53-orangepi-plus2e  running on the Orange PI PC, but there was no Ethernet because the +2E has a gigabit  adapter.  So I copied over the  sun8i-h3-orangepi-pc.dtb  from the image LibreELEC-H3.arm-13.0-nightly-20240929-8602b53-orangepi-pc.  When I rebooted using that FDT, I had working Ethernet

**Comment by jernejsk** [comment]
Can you try fix in #9343?

**Comment by NickelNuts** [comment]
> Can you try fix in #9343?

Does this get reflected in the nightly builds, or should I set up a cross-compiler, and build?

**Comment by jernejsk** [comment]
You have to build it yourself using command `PROJECT=Allwinner ARCH=arm DEVICE=H3 UBOOT_SYSTEM=orangepi-pc make image`. See https://wiki.libreelec.tv/development/build-basics for how to set up environment.

**Comment by NickelNuts** [comment]
OK thanks.  I have  the compiler running.  I manually deleted 0011-DO-NOT-MERGE-sunxi-Enable-remoteproc-on-some-H3-boar.patch and added 0011-DO-NOT-MERGE-sunxi-Enable-remoteproc-on-some-H3.patch

**Comment by NickelNuts** [comment]
Now I see I should have built for version 13 instead of 12,  I can redo it if it makes a difference
