### ISSUE TITLE
[BUG] LibreELEC 12, 11 and 10 major problems with Rpi2 and Rpi3 computers

### ISSUE THREAD

**Issue by BugfinderPro135** [LibreELEC/LibreELEC.tv#9338]
Been using RPi2 and RPi3 computers with LibreElec 9 (kodi 18.9) for years, mostly with iplayer www and IPTV simple client, the latter with a custom streams.

I started testing kodi 20 and 21 on cheap Chinese Android TV sticks, which worked fine for the iplayer and these streams. The streams still also work on LibreElec 9 too, but alas iplayer www does not.

I installed LE 10, 11 and 12 on a RPi3 and iplayer www didn't work well as it was not displaying smooth tv - was a bit jittery, looked like lost frames. Simple IPTV client didn't work at all well, audio and video going 5s out of sync, picture break up - on the very same RPi3 where LE9 works perfectly with Simple IPTV client.

Something has gone seriously wrong with LE10-12 on RPi2 and RPi3 for this to happen, yet nobody else has reported and problems like this in the 4 years of it's release?

I'm going to try OSMC on the pi3 next to see if it works... I fear, however, LibreElec have messed up big time here, since the change to Python3....

**Comment by heitbaum** [comment]
Please head over to the forum for support. https://forum.libreelec.tv/
