### ISSUE TITLE
[BUG] curl does not build on arm/aarch when LE is built with DEBUG

### ISSUE THREAD

**Issue by heitbaum** [LibreELEC/LibreELEC.tv#9607]
### Describe the bug

release build works fine. Something to do with the optimization of not -O / -O2 in glibc?

### How to reproduce
1. `PROJECT=RPi ARCH=aarch64 DEVICE=RPi4 DEBUG=yes s/build curl`

### Information
 - LibreELEC Version: [e.g. 9.2.1] LE13
 - Hardware Platform: [e.g. RPi3] RPi2 and RPi4

### Log file

```
In file included from /LibreELEC.tv/build.LibreELEC-RPi4.aarch64-13.0-devel-debug/build/curl-8.10.1/lib/easy.c:78:
/LibreELEC.tv/build.LibreELEC-RPi4.aarch64-13.0-devel-debug/build/curl-8.10.1/lib/easy_lock.h: In function 'curl_global_init':
/LibreELEC.tv/build.LibreELEC-RPi4.aarch64-13.0-devel-debug/build/curl-8.10.1/lib/easy_lock.h:72:20: error: inlining failed in call to 'curl_simple_lock_lock': function not considered for inlining [-Werror=inline]
``` 

### Context

Similar to
- https://docs.yoctoproject.org/pipermail/yocto/2015-August/026252.html

**Comment by mglae** [comment]
Should be an error on all platforms, did the fix for Generic debug build (and forgot it)
